latex_names <- list(
  y_gap = "${\\tilde{y}_t}$",                               # Scotland output gap
  pi_h = "${\\pi_{H,t}}$",                                  # Scotland domestic inflation
  y_nat = "${y^{nat}_t}$",                                 # Scotland natural output
  r_nat = "${r^{nat}_t}$",                                 # Scotland natural interest rate
  s_nat = "${s^{nat}_t}$",                                 # Scotland natural terms of trade
  y = "${y_t}$",                                           # Scotland output
  s_gap = "${\\tilde{s}_t}$",                               # Scotland terms of trade gap
  s = "${s_t}$",                                           # Scotland terms of trade
  pi = "${\\pi_t}$",                                       # Scotland CPI inflation
  n = "${n_t}$",                                           # Scotland employment
  r_real = "${r^r_t}$",                                    # Scotland real interest rate
  w = "${w_t}$",                                           # Scotland nominal wage
  nx = "${nx_t}$",                                         # Scotland net exports
  c = "${c_t}$",                                           # Scotland consumption
  yhat = "${\\hat{y}_t}$",                                 # Scotland output deviation from steady state
  p_h = "${p_H_t}$",                                       # Scotland domestic price level
  p = "${p_t}$",                                           # Scotland CPI
  er = "${e_t}$",                                          # Scotland nominal exchange rate
  d_er = "${\\Delta e_t}$",                                # Scotland nominal exchange rate growth
  y_star = "${y^*_t}$",                                    # World output
  a = "${a_t}$",                                           # Scotland AR(1) technology shock process
  z = "${z_t}$",                                           # Scotland AR(1) preference shock process
  wp = "${wp_t}$",                                         # Scotland real wage
  y_gap_f = "${\\tilde{y^*}}$",                            # rUK output gap
  pi_h_f = "${\\pi^*_{H,t}}$",                             # rUK domestic inflation
  y_nat_f = "${y^{*nat}_t}$",                              # rUK natural output
  r_nat_f = "${r^{*nat}_t}$",                              # rUK natural interest rate
  s_nat_f = "${s^{*nat}_t}$",                              # rUK natural terms of trade
  y_f = "${y^*_t}$",                                       # rUK output
  s_gap_f = "${\\tilde{s^*}_t}$",                          # rUK terms of trade gap
  s_f = "${s^*_t}$",                                       # rUK terms of trade
  pi_f = "${\\pi^*_t}$",                                   # rUK CPI inflation
  n_f = "${n^*_t}$",                                       # rUK employment
  r_real_f = "${r^r_t}$",                                  # rUK real interest rate
  w_f = "${w^*_t}$",                                       # rUK nominal wage
  nx_f = "${nx^*_t}$",                                     # rUK net exports in terms of domestic output
  c_f = "${c^*_t}$",                                       # rUK consumption
  yhat_f = "${\\hat{y}^*_t}$",                             # rUK output deviation from steady state
  p_h_f = "${p^*_{H, t}}$",                                # rUK domestic price level
  p_f = "${p^*_t}$",                                       # rUK CPI
  er_f = "${e^*_t}$",                                      # rUK nominal exchange rate
  d_er_f = "${\\Delta e^*_t}$",                            # rUK nominal exchange rate growth
  a_f = "${a^*_t}$",                                       # rUK AR(1) technology shock process
  z_f = "${z^*_t}$",                                       # rUK AR(1) preference shock process
  wp_f = "${wp^*_t}$",                                     # rUK real wage
  p_h_uk = "",                                             # Placeholder for p_h_uk
  tr = "${tr_t}$",                                         # Scotland tax revenue
  tr_f = "${tr^*_t}$",                                     # rUK tax revenue
  g = "${g_t}$",                                           # Scotland government spending
  g_f = "${g^*_t}$",                                       # rUK government spending
  b = "${b_t}$",                                           # Scotland government bonds
  b_f = "${b^*_t}$",                                       # rUK government bonds
  debt = "${d_t}$",                                        # rUK government debt
  debt_f = "${d^{*}_t}$",                                  # rUK government debt
  tau = "${\\tau_t}$",                                     # Scotland labour tax
  tau_f = "${\\tau^*_t}$",                                 # rUK labour tax
  g_uk = "${g^{UK}_t}$",                                   # UK government spending
  tr_uk = "${tr^{UK}_t}$",                                 # UK tax revenue
  b_uk = "${b^{UK}_t}$",                                   # UK government bonds
  debt_uk = "${d^{UK}_t}$",                                # UK government debt
  tau_uk = "${\\tau^{UK}_t}$",                             # UK labour tax
  interest = "${i_t}$",                                    # Scotland interest rate
  interest_f = "${i^*_t}$",                                # rUK interest rate
  interest_uk = "${i^{UK}_t}$",                            # UK interest rate
  nu = "${\\nu_t}$",                                       # Scotland AR(1) monetary policy shock process
  nu_f = "${\\nu^*_t}$",                                   # rUK AR(1) monetary policy shock process
  nu_uk = "${\\nu^{UK}_t}$"                                # UK AR(1) monetary policy shock process
)
