%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'dissertation';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(7,1);
M_.exo_names_tex = cell(7,1);
M_.exo_names_long = cell(7,1);
M_.exo_names(1) = {'eps_nu'};
M_.exo_names_tex(1) = {'{\varepsilon^\nu}'};
M_.exo_names_long(1) = {'monetary policy shock'};
M_.exo_names(2) = {'eps_a'};
M_.exo_names_tex(2) = {'{\varepsilon^a}'};
M_.exo_names_long(2) = {'technology shock'};
M_.exo_names(3) = {'eps_z'};
M_.exo_names_tex(3) = {'{\varepsilon^z}'};
M_.exo_names_long(3) = {'preference shock'};
M_.exo_names(4) = {'p_star'};
M_.exo_names_tex(4) = {'{p^*}'};
M_.exo_names_long(4) = {'world price level'};
M_.exo_names(5) = {'eps_nu_f'};
M_.exo_names_tex(5) = {'{\varepsilon^{f,\nu}}'};
M_.exo_names_long(5) = {'monetary policy shock'};
M_.exo_names(6) = {'eps_a_f'};
M_.exo_names_tex(6) = {'{\varepsilon^{f,a}}'};
M_.exo_names_long(6) = {'technology shock'};
M_.exo_names(7) = {'eps_z_f'};
M_.exo_names_tex(7) = {'{\varepsilon^{f,z}}'};
M_.exo_names_long(7) = {'preference shock'};
M_.endo_names = cell(60,1);
M_.endo_names_tex = cell(60,1);
M_.endo_names_long = cell(60,1);
M_.endo_names(1) = {'y_gap'};
M_.endo_names_tex(1) = {'{\tilde{y}}'};
M_.endo_names_long(1) = {'output gap'};
M_.endo_names(2) = {'pi_h'};
M_.endo_names_tex(2) = {'{\pi_H}'};
M_.endo_names_long(2) = {'domestic inflation'};
M_.endo_names(3) = {'i'};
M_.endo_names_tex(3) = {'{i}'};
M_.endo_names_long(3) = {'nominal interest rate'};
M_.endo_names(4) = {'y_nat'};
M_.endo_names_tex(4) = {'{y^{n}}'};
M_.endo_names_long(4) = {'natural output'};
M_.endo_names(5) = {'r_nat'};
M_.endo_names_tex(5) = {'{r^{n}}'};
M_.endo_names_long(5) = {'natural interest rate'};
M_.endo_names(6) = {'s_nat'};
M_.endo_names_tex(6) = {'{s^{n}}'};
M_.endo_names_long(6) = {'natural terms of trade'};
M_.endo_names(7) = {'y'};
M_.endo_names_tex(7) = {'{y}'};
M_.endo_names_long(7) = {'output'};
M_.endo_names(8) = {'s_gap'};
M_.endo_names_tex(8) = {'{\tilde{s}}'};
M_.endo_names_long(8) = {'terms of trade gap'};
M_.endo_names(9) = {'s'};
M_.endo_names_tex(9) = {'{s}'};
M_.endo_names_long(9) = {'terms of trade'};
M_.endo_names(10) = {'pi'};
M_.endo_names_tex(10) = {'{\pi}'};
M_.endo_names_long(10) = {'CPI inflation'};
M_.endo_names(11) = {'n'};
M_.endo_names_tex(11) = {'{n}'};
M_.endo_names_long(11) = {'employment'};
M_.endo_names(12) = {'r_real'};
M_.endo_names_tex(12) = {'{r^r}'};
M_.endo_names_long(12) = {'real interest rate'};
M_.endo_names(13) = {'w'};
M_.endo_names_tex(13) = {'{w}'};
M_.endo_names_long(13) = {'nominal wage'};
M_.endo_names(14) = {'nx'};
M_.endo_names_tex(14) = {'{nx}'};
M_.endo_names_long(14) = {'net exports in terms of domestic outout'};
M_.endo_names(15) = {'c'};
M_.endo_names_tex(15) = {'{c}'};
M_.endo_names_long(15) = {'consumption'};
M_.endo_names(16) = {'yhat'};
M_.endo_names_tex(16) = {'{\hat y}'};
M_.endo_names_long(16) = {'output deviation from steady state'};
M_.endo_names(17) = {'p_h'};
M_.endo_names_tex(17) = {'{p_H}'};
M_.endo_names_long(17) = {'domestic price level'};
M_.endo_names(18) = {'p'};
M_.endo_names_tex(18) = {'{p}'};
M_.endo_names_long(18) = {'CPI'};
M_.endo_names(19) = {'er'};
M_.endo_names_tex(19) = {'{e}'};
M_.endo_names_long(19) = {'Nominal exchange rate'};
M_.endo_names(20) = {'d_er'};
M_.endo_names_tex(20) = {'{\Delta e}'};
M_.endo_names_long(20) = {'Nominal exchange rate growth'};
M_.endo_names(21) = {'y_star'};
M_.endo_names_tex(21) = {'{y^*}'};
M_.endo_names_long(21) = {'world output'};
M_.endo_names(22) = {'a'};
M_.endo_names_tex(22) = {'{a}'};
M_.endo_names_long(22) = {'AR(1) technology shock process'};
M_.endo_names(23) = {'nu'};
M_.endo_names_tex(23) = {'{\nu}'};
M_.endo_names_long(23) = {'AR(1) monetary policy shock process'};
M_.endo_names(24) = {'z'};
M_.endo_names_tex(24) = {'{z}'};
M_.endo_names_long(24) = {'AR(1) preference shock process'};
M_.endo_names(25) = {'r_real_ann'};
M_.endo_names_tex(25) = {'{r^{r,ann}}'};
M_.endo_names_long(25) = {'annualized real interest rate'};
M_.endo_names(26) = {'i_ann'};
M_.endo_names_tex(26) = {'{i^{ann}}'};
M_.endo_names_long(26) = {'annualized nominal interest rate'};
M_.endo_names(27) = {'r_nat_ann'};
M_.endo_names_tex(27) = {'{r^{nat,ann}}'};
M_.endo_names_long(27) = {'annualized natural interest rate'};
M_.endo_names(28) = {'pi_ann'};
M_.endo_names_tex(28) = {'{\pi^{ann}}'};
M_.endo_names_long(28) = {'annualized CPI inflation rate'};
M_.endo_names(29) = {'pi_h_ann'};
M_.endo_names_tex(29) = {'{\pi_H^{ann}}'};
M_.endo_names_long(29) = {'annualized domestic inflation rate'};
M_.endo_names(30) = {'y_gap_f'};
M_.endo_names_tex(30) = {'{\tilde{y^f}}'};
M_.endo_names_long(30) = {'output gap'};
M_.endo_names(31) = {'pi_h_f'};
M_.endo_names_tex(31) = {'{\pi^f_H}'};
M_.endo_names_long(31) = {'domestic inflation'};
M_.endo_names(32) = {'y_nat_f'};
M_.endo_names_tex(32) = {'{{y^f}^{n}}'};
M_.endo_names_long(32) = {'natural output'};
M_.endo_names(33) = {'r_nat_f'};
M_.endo_names_tex(33) = {'{{r^f}^{n}}'};
M_.endo_names_long(33) = {'natural interest rate'};
M_.endo_names(34) = {'s_nat_f'};
M_.endo_names_tex(34) = {'{{s^f}^{n}}'};
M_.endo_names_long(34) = {'natural terms of trade'};
M_.endo_names(35) = {'y_f'};
M_.endo_names_tex(35) = {'{y^f}'};
M_.endo_names_long(35) = {'output'};
M_.endo_names(36) = {'s_gap_f'};
M_.endo_names_tex(36) = {'{\tilde{s^f}}'};
M_.endo_names_long(36) = {'terms of trade gap'};
M_.endo_names(37) = {'s_f'};
M_.endo_names_tex(37) = {'{s^f}'};
M_.endo_names_long(37) = {'terms of trade'};
M_.endo_names(38) = {'pi_f'};
M_.endo_names_tex(38) = {'{\pi^f}'};
M_.endo_names_long(38) = {'CPI inflation'};
M_.endo_names(39) = {'n_f'};
M_.endo_names_tex(39) = {'{n^f}'};
M_.endo_names_long(39) = {'employment'};
M_.endo_names(40) = {'r_real_f'};
M_.endo_names_tex(40) = {'{r^r}'};
M_.endo_names_long(40) = {'real interest rate'};
M_.endo_names(41) = {'w_f'};
M_.endo_names_tex(41) = {'{w^f}'};
M_.endo_names_long(41) = {'nominal wage'};
M_.endo_names(42) = {'nx_f'};
M_.endo_names_tex(42) = {'{nx^f}'};
M_.endo_names_long(42) = {'net exports in terms of domestic outout'};
M_.endo_names(43) = {'c_f'};
M_.endo_names_tex(43) = {'{c^f}'};
M_.endo_names_long(43) = {'consumption'};
M_.endo_names(44) = {'yhat_f'};
M_.endo_names_tex(44) = {'{\hat y^f}'};
M_.endo_names_long(44) = {'output deviation from steady state'};
M_.endo_names(45) = {'p_h_f'};
M_.endo_names_tex(45) = {'{p^f_H}'};
M_.endo_names_long(45) = {'domestic price level'};
M_.endo_names(46) = {'p_f'};
M_.endo_names_tex(46) = {'{p^f}'};
M_.endo_names_long(46) = {'CPI'};
M_.endo_names(47) = {'er_f'};
M_.endo_names_tex(47) = {'{e^f}'};
M_.endo_names_long(47) = {'Nominal exchange rate'};
M_.endo_names(48) = {'d_er_f'};
M_.endo_names_tex(48) = {'{\Delta e^f}'};
M_.endo_names_long(48) = {'Nominal exchange rate growth'};
M_.endo_names(49) = {'a_f'};
M_.endo_names_tex(49) = {'{a^f}'};
M_.endo_names_long(49) = {'AR(1) technology shock process'};
M_.endo_names(50) = {'nu_f'};
M_.endo_names_tex(50) = {'{\nu^f}'};
M_.endo_names_long(50) = {'AR(1) monetary policy shock process'};
M_.endo_names(51) = {'z_f'};
M_.endo_names_tex(51) = {'{z^f}'};
M_.endo_names_long(51) = {'AR(1) preference shock process'};
M_.endo_names(52) = {'r_real_ann_f'};
M_.endo_names_tex(52) = {'{r^{f,r,ann}}'};
M_.endo_names_long(52) = {'annualized real interest rate'};
M_.endo_names(53) = {'i_ann_f'};
M_.endo_names_tex(53) = {'{i^{f,ann}}'};
M_.endo_names_long(53) = {'annualized nominal interest rate'};
M_.endo_names(54) = {'r_nat_ann_f'};
M_.endo_names_tex(54) = {'{r^{f,nat,ann}}'};
M_.endo_names_long(54) = {'annualized natural interest rate'};
M_.endo_names(55) = {'pi_ann_f'};
M_.endo_names_tex(55) = {'{\pi^{f,ann}}'};
M_.endo_names_long(55) = {'annualized CPI inflation rate'};
M_.endo_names(56) = {'pi_h_ann_f'};
M_.endo_names_tex(56) = {'{\pi_H^{f,ann}}'};
M_.endo_names_long(56) = {'annualized domestic inflation rate'};
M_.endo_names(57) = {'AUX_ENDO_LAG_1_1'};
M_.endo_names_tex(57) = {'AUX\_ENDO\_LAG\_1\_1'};
M_.endo_names_long(57) = {'AUX_ENDO_LAG_1_1'};
M_.endo_names(58) = {'AUX_ENDO_LAG_30_1'};
M_.endo_names_tex(58) = {'AUX\_ENDO\_LAG\_30\_1'};
M_.endo_names_long(58) = {'AUX_ENDO_LAG_30_1'};
M_.endo_names(59) = {'AUX_ENDO_LAG_15_1'};
M_.endo_names_tex(59) = {'AUX\_ENDO\_LAG\_15\_1'};
M_.endo_names_long(59) = {'AUX_ENDO_LAG_15_1'};
M_.endo_names(60) = {'AUX_ENDO_LAG_43_1'};
M_.endo_names_tex(60) = {'AUX\_ENDO\_LAG\_43\_1'};
M_.endo_names_long(60) = {'AUX_ENDO_LAG_43_1'};
M_.endo_partitions = struct();
M_.param_names = cell(28,1);
M_.param_names_tex = cell(28,1);
M_.param_names_long = cell(28,1);
M_.param_names(1) = {'siggma'};
M_.param_names_tex(1) = {'{\sigma}'};
M_.param_names_long(1) = {'inverse EIS'};
M_.param_names(2) = {'betta'};
M_.param_names_tex(2) = {'{\beta}'};
M_.param_names_long(2) = {'discount factor'};
M_.param_names(3) = {'varphi'};
M_.param_names_tex(3) = {'{\varphi}'};
M_.param_names_long(3) = {'inverse Frisch elasticity'};
M_.param_names(4) = {'alppha'};
M_.param_names_tex(4) = {'{\alpha}'};
M_.param_names_long(4) = {'capital share'};
M_.param_names(5) = {'epsilon'};
M_.param_names_tex(5) = {'{\epsilon}'};
M_.param_names_long(5) = {'demand elasticity'};
M_.param_names(6) = {'theta'};
M_.param_names_tex(6) = {'{\theta}'};
M_.param_names_long(6) = {'Calvo parameter'};
M_.param_names(7) = {'upsilon'};
M_.param_names_tex(7) = {'{\upsilon}'};
M_.param_names_long(7) = {'openness parameter'};
M_.param_names(8) = {'eta'};
M_.param_names_tex(8) = {'{\eta}'};
M_.param_names_long(8) = {'substitutability foreign/domestic goods'};
M_.param_names(9) = {'rho_a'};
M_.param_names_tex(9) = {'{\rho_a}'};
M_.param_names_long(9) = {'autocorrelation technology shock'};
M_.param_names(10) = {'rho_nu'};
M_.param_names_tex(10) = {'{\rho_{\nu}}'};
M_.param_names_long(10) = {'autocorrelation monetary policy shock'};
M_.param_names(11) = {'rho_y_star'};
M_.param_names_tex(11) = {'{\rho_{y^*}}'};
M_.param_names_long(11) = {'autocorrelation world output growth shock'};
M_.param_names(12) = {'rho_z'};
M_.param_names_tex(12) = {'{\rho_{z}}'};
M_.param_names_long(12) = {'autocorrelation preference shock'};
M_.param_names(13) = {'phi_pi'};
M_.param_names_tex(13) = {'{\phi_{\pi}}'};
M_.param_names_long(13) = {'inflation feedback Taylor Rule'};
M_.param_names(14) = {'phi_y'};
M_.param_names_tex(14) = {'{\phi_{y}}'};
M_.param_names_long(14) = {'output feedback Taylor Rule'};
M_.param_names(15) = {'siggma_f'};
M_.param_names_tex(15) = {'{\sigma}'};
M_.param_names_long(15) = {'inverse EIS'};
M_.param_names(16) = {'betta_f'};
M_.param_names_tex(16) = {'{\beta}'};
M_.param_names_long(16) = {'discount factor'};
M_.param_names(17) = {'varphi_f'};
M_.param_names_tex(17) = {'{\varphi}'};
M_.param_names_long(17) = {'inverse Frisch elasticity'};
M_.param_names(18) = {'alppha_f'};
M_.param_names_tex(18) = {'{\alpha}'};
M_.param_names_long(18) = {'capital share'};
M_.param_names(19) = {'epsilon_f'};
M_.param_names_tex(19) = {'{\epsilon}'};
M_.param_names_long(19) = {'demand elasticity'};
M_.param_names(20) = {'theta_f'};
M_.param_names_tex(20) = {'{\theta}'};
M_.param_names_long(20) = {'Calvo parameter'};
M_.param_names(21) = {'upsilon_f'};
M_.param_names_tex(21) = {'{\upsilon}'};
M_.param_names_long(21) = {'openness parameter'};
M_.param_names(22) = {'eta_f'};
M_.param_names_tex(22) = {'{\eta}'};
M_.param_names_long(22) = {'substitutability foreign/domestic goods'};
M_.param_names(23) = {'rho_a_f'};
M_.param_names_tex(23) = {'{\rho_a}'};
M_.param_names_long(23) = {'autocorrelation technology shock'};
M_.param_names(24) = {'rho_nu_f'};
M_.param_names_tex(24) = {'{\rho_{\nu}}'};
M_.param_names_long(24) = {'autocorrelation monetary policy shock'};
M_.param_names(25) = {'rho_y_star_f'};
M_.param_names_tex(25) = {'{\rho_{y^*}}'};
M_.param_names_long(25) = {'autocorrelation world output growth shock'};
M_.param_names(26) = {'rho_z_f'};
M_.param_names_tex(26) = {'{\rho_{z}}'};
M_.param_names_long(26) = {'autocorrelation preference shock'};
M_.param_names(27) = {'phi_pi_f'};
M_.param_names_tex(27) = {'{\phi_{\pi}}'};
M_.param_names_long(27) = {'inflation feedback Taylor Rule'};
M_.param_names(28) = {'phi_y_f'};
M_.param_names_tex(28) = {'{\phi_{y}}'};
M_.param_names_long(28) = {'output feedback Taylor Rule'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 60;
M_.param_nbr = 28;
M_.orig_endo_nbr = 56;
M_.aux_vars(1).endo_index = 57;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 2;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(1).orig_expr = 'pi_h(-1)';
M_.aux_vars(2).endo_index = 58;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 31;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(2).orig_expr = 'pi_h_f(-1)';
M_.aux_vars(3).endo_index = 59;
M_.aux_vars(3).type = 1;
M_.aux_vars(3).orig_index = 16;
M_.aux_vars(3).orig_lead_lag = -1;
M_.aux_vars(3).orig_expr = 'yhat(-1)';
M_.aux_vars(4).endo_index = 60;
M_.aux_vars(4).type = 1;
M_.aux_vars(4).orig_index = 44;
M_.aux_vars(4).orig_lead_lag = -1;
M_.aux_vars(4).orig_expr = 'yhat_f(-1)';
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 56;
M_.eq_nbr = 60;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 2;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 2;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 2;
M_.lead_lag_incidence = [
 0 23 83;
 1 24 84;
 0 25 0;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 2 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 0 36 0;
 0 37 0;
 3 38 0;
 4 39 0;
 5 40 0;
 6 41 0;
 0 42 0;
 0 43 0;
 7 44 0;
 8 45 0;
 9 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 85;
 10 53 86;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 11 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 12 66 0;
 13 67 0;
 14 68 0;
 15 69 0;
 0 70 0;
 16 71 0;
 17 72 0;
 18 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 19 79 0;
 20 80 0;
 21 81 0;
 22 82 0;]';
M_.nstatic = 36;
M_.nfwrd   = 2;
M_.npred   = 20;
M_.nboth   = 2;
M_.nsfwrd   = 4;
M_.nspred   = 22;
M_.ndynamic   = 24;
M_.dynamic_tmp_nbr = [10; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'New Keynesian Phillips Curve (eq. 37)' ;
  2 , 'name' , 'Dynamic IS Curve (eq. 29)' ;
  3 , 'name' , 'Natural output (eq. 35)' ;
  4 , 'name' , 'Natural rate of interest (eq. 38)' ;
  5 , 'name' , 'Natural terms of trade (below eq. (35))' ;
  6 , 'name' , 'Terms of trade gap (middle p. 238)' ;
  7 , 'name' , 'Output' ;
  8 , 'name' , ' Terms of trade, p. 238' ;
  9 , 'name' , 'CPI inflation (13)' ;
  10 , 'name' , 'Production function (eq. 32)' ;
  11 , 'name' , 'Definition real interest rate' ;
  12 , 'name' , 'Monetary policy shock, below eq. (39)' ;
  13 , 'name' , 'TFP shock, top of p. 233' ;
  14 , 'name' , 'Preference shock, top of p. 227' ;
  15 , 'name' , 'FOC wage, eq. (11)' ;
  16 , 'name' , 'net exports, eq. (31)' ;
  17 , 'name' , 'consumption determined by resource constraint, p. 236' ;
  18 , 'name' , 'y_star' ;
  19 , 'name' , 'Annualized nominal interest rate' ;
  20 , 'name' , 'Annualized real interest rate' ;
  21 , 'name' , ' Annualized natural interest rate' ;
  22 , 'name' , 'Annualized CPI inflation' ;
  23 , 'name' , 'Annualized domestic inflation' ;
  24 , 'name' , 'Output deviation from steady state' ;
  25 , 'name' , 'Domestic price level, p. 229' ;
  26 , 'name' , 'CPI definition' ;
  27 , 'name' , 'Nominal exchange rate' ;
  28 , 'name' , 'Definiion exchange rate growth' ;
  29 , 'name' , 'i' ;
  30 , 'name' , 'FOREIGN New Keynesian Phillips Curve (eq. 37)' ;
  31 , 'name' , 'FOREIGN Dynamic IS Curve (eq. 29)' ;
  32 , 'name' , 'FOREIGN Natural output (eq. 35)' ;
  33 , 'name' , 'FOREIGN Natural rate of interest (eq. 38)' ;
  34 , 'name' , 'FOREIGN Natural terms of trade (below eq. (35))' ;
  35 , 'name' , 'FOREIGN Terms of trade gap (middle p. 238)' ;
  36 , 'name' , 'FOREIGN Output' ;
  37 , 'name' , 'FOREIGN  Terms of trade, p. 238' ;
  38 , 'name' , 'FOREIGN CPI inflation (13)' ;
  39 , 'name' , 'FOREIGN Production function (eq. 32)' ;
  40 , 'name' , 'FOREIGN Definition real interest rate' ;
  41 , 'name' , 'FOREIGN Monetary policy shock, below eq. (39)' ;
  42 , 'name' , 'FOREIGN TFP shock, top of p. 233' ;
  43 , 'name' , 'FOREIGN Preference shock, top of p. 227' ;
  44 , 'name' , 'FOREIGN FOC wage, eq. (11)' ;
  45 , 'name' , 'FOREIGN net exports, eq. (31)' ;
  46 , 'name' , 'FOREIGN consumption determined by resource constraint, p. 236' ;
  47 , 'name' , 'FOREIGN Annualized nominal interest rate' ;
  48 , 'name' , 'FOREIGN Annualized real interest rate' ;
  49 , 'name' , 'FOREIGN  Annualized natural interest rate' ;
  50 , 'name' , 'FOREIGN Annualized CPI inflation' ;
  51 , 'name' , 'FOREIGN Annualized domestic inflation' ;
  52 , 'name' , 'FOREIGN Output deviation from steady state' ;
  53 , 'name' , 'FOREIGN Domestic price level, p. 229' ;
  54 , 'name' , 'FOREIGN CPI definition' ;
  55 , 'name' , 'FOREIGN Nominal exchange rate' ;
  56 , 'name' , 'FOREIGN Definiion exchange rate growth' ;
};
M_.mapping.y_gap.eqidx = [1 2 6 7 ];
M_.mapping.pi_h.eqidx = [1 2 9 11 23 25 29 ];
M_.mapping.i.eqidx = [2 11 19 29 31 40 47 ];
M_.mapping.y_nat.eqidx = [3 5 7 ];
M_.mapping.r_nat.eqidx = [2 4 21 ];
M_.mapping.s_nat.eqidx = [5 8 ];
M_.mapping.y.eqidx = [7 10 17 24 ];
M_.mapping.s_gap.eqidx = [6 8 ];
M_.mapping.s.eqidx = [8 9 16 17 27 ];
M_.mapping.pi.eqidx = [9 22 26 ];
M_.mapping.n.eqidx = [10 15 ];
M_.mapping.r_real.eqidx = [11 20 ];
M_.mapping.w.eqidx = [15 ];
M_.mapping.nx.eqidx = [16 17 ];
M_.mapping.c.eqidx = [15 17 ];
M_.mapping.yhat.eqidx = [24 29 ];
M_.mapping.p_h.eqidx = [25 27 ];
M_.mapping.p.eqidx = [15 26 ];
M_.mapping.er.eqidx = [27 28 ];
M_.mapping.d_er.eqidx = [28 ];
M_.mapping.y_star.eqidx = [18 ];
M_.mapping.a.eqidx = [3 4 10 13 ];
M_.mapping.nu.eqidx = [12 29 ];
M_.mapping.z.eqidx = [3 4 5 14 16 ];
M_.mapping.r_real_ann.eqidx = [20 ];
M_.mapping.i_ann.eqidx = [19 ];
M_.mapping.r_nat_ann.eqidx = [21 ];
M_.mapping.pi_ann.eqidx = [22 ];
M_.mapping.pi_h_ann.eqidx = [23 ];
M_.mapping.y_gap_f.eqidx = [30 31 35 36 ];
M_.mapping.pi_h_f.eqidx = [29 30 31 38 40 51 53 ];
M_.mapping.y_nat_f.eqidx = [32 34 36 ];
M_.mapping.r_nat_f.eqidx = [31 33 49 ];
M_.mapping.s_nat_f.eqidx = [34 37 ];
M_.mapping.y_f.eqidx = [36 39 46 52 ];
M_.mapping.s_gap_f.eqidx = [35 37 ];
M_.mapping.s_f.eqidx = [37 38 45 46 55 ];
M_.mapping.pi_f.eqidx = [38 50 54 ];
M_.mapping.n_f.eqidx = [39 44 ];
M_.mapping.r_real_f.eqidx = [40 48 ];
M_.mapping.w_f.eqidx = [44 ];
M_.mapping.nx_f.eqidx = [45 46 ];
M_.mapping.c_f.eqidx = [44 46 ];
M_.mapping.yhat_f.eqidx = [29 52 ];
M_.mapping.p_h_f.eqidx = [53 55 ];
M_.mapping.p_f.eqidx = [44 54 ];
M_.mapping.er_f.eqidx = [55 56 ];
M_.mapping.d_er_f.eqidx = [56 ];
M_.mapping.a_f.eqidx = [32 33 39 42 ];
M_.mapping.nu_f.eqidx = [29 41 ];
M_.mapping.z_f.eqidx = [32 33 34 43 45 ];
M_.mapping.r_real_ann_f.eqidx = [48 ];
M_.mapping.i_ann_f.eqidx = [47 ];
M_.mapping.r_nat_ann_f.eqidx = [49 ];
M_.mapping.pi_ann_f.eqidx = [50 ];
M_.mapping.pi_h_ann_f.eqidx = [51 ];
M_.mapping.eps_nu.eqidx = [12 ];
M_.mapping.eps_a.eqidx = [13 ];
M_.mapping.eps_z.eqidx = [14 ];
M_.mapping.p_star.eqidx = [27 55 ];
M_.mapping.eps_nu_f.eqidx = [41 ];
M_.mapping.eps_a_f.eqidx = [42 ];
M_.mapping.eps_z_f.eqidx = [43 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [2 9 16 17 18 19 22 23 24 31 37 44 45 46 47 49 50 51 57 58 59 60 ];
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(60, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(28, 1);
M_.endo_trends = struct('deflator', cell(60, 1), 'log_deflator', cell(60, 1), 'growth_factor', cell(60, 1), 'log_growth_factor', cell(60, 1));
M_.NNZDerivatives = [180; 0; -1; ];
M_.static_tmp_nbr = [10; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(2) = 0.99;
betta = M_.params(2);
M_.params(1) = 1;
siggma = M_.params(1);
M_.params(3) = 5;
varphi = M_.params(3);
M_.params(4) = 0.25;
alppha = M_.params(4);
M_.params(5) = 9;
epsilon = M_.params(5);
M_.params(6) = 0.75;
theta = M_.params(6);
M_.params(7) = 0.4;
upsilon = M_.params(7);
M_.params(10) = 0.5;
rho_nu = M_.params(10);
M_.params(9) = 0.9;
rho_a = M_.params(9);
M_.params(11) = 0;
rho_y_star = M_.params(11);
M_.params(13) = 1.5;
phi_pi = M_.params(13);
M_.params(14) = 0.125;
phi_y = M_.params(14);
M_.params(8) = 1;
eta = M_.params(8);
M_.params(12) = 0.5;
rho_z = M_.params(12);
M_.params(16) = 0.99;
betta_f = M_.params(16);
M_.params(15) = 1;
siggma_f = M_.params(15);
M_.params(17) = 5;
varphi_f = M_.params(17);
M_.params(18) = 0.25;
alppha_f = M_.params(18);
M_.params(19) = 6;
epsilon_f = M_.params(19);
M_.params(20) = 0.75;
theta_f = M_.params(20);
M_.params(21) = 0.4;
upsilon_f = M_.params(21);
M_.params(24) = 0.5;
rho_nu_f = M_.params(24);
M_.params(23) = 0.9;
rho_a_f = M_.params(23);
M_.params(25) = 0;
rho_y_star_f = M_.params(25);
M_.params(27) = 1.5;
phi_pi_f = M_.params(27);
M_.params(28) = 0.125;
phi_y_f = M_.params(28);
M_.params(22) = 1;
eta_f = M_.params(22);
M_.params(26) = 0.5;
rho_z_f = M_.params(26);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0.0625;
M_.Sigma_e(5, 5) = 0.0625;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 15;
options_.order = 1;
var_list_ = {'y_gap';'y_gap_f'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
