%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'dissertation';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(9,1);
M_.exo_names_tex = cell(9,1);
M_.exo_names_long = cell(9,1);
M_.exo_names(1) = {'eps_a'};
M_.exo_names_tex(1) = {'{\varepsilon^a}'};
M_.exo_names_long(1) = {'Technology shock'};
M_.exo_names(2) = {'eps_z'};
M_.exo_names_tex(2) = {'{\varepsilon^z}'};
M_.exo_names_long(2) = {'Preference shock'};
M_.exo_names(3) = {'eps_a_f'};
M_.exo_names_tex(3) = {'{\varepsilon^{f,a}}'};
M_.exo_names_long(3) = {'technology shock'};
M_.exo_names(4) = {'eps_z_f'};
M_.exo_names_tex(4) = {'{\varepsilon^{f,z}}'};
M_.exo_names_long(4) = {'preference shock'};
M_.exo_names(5) = {'eps_nu_uk'};
M_.exo_names_tex(5) = {'{\varepsilon^\nu}'};
M_.exo_names_long(5) = {'Monetary policy shock'};
M_.exo_names(6) = {'eps_g'};
M_.exo_names_tex(6) = {'{\varepsilon^{\tau}}'};
M_.exo_names_long(6) = {'Government Spending shock (Scotland)'};
M_.exo_names(7) = {'eps_g_f'};
M_.exo_names_tex(7) = {'{\varepsilon^{\tau,f}}'};
M_.exo_names_long(7) = {'Government Spending shock (rUK)'};
M_.exo_names(8) = {'eps_y_star'};
M_.exo_names_tex(8) = {'{\varepsilon^y}'};
M_.exo_names_long(8) = {'world output growth shock'};
M_.exo_names(9) = {'p_star'};
M_.exo_names_tex(9) = {'{p^*}'};
M_.exo_names_long(9) = {'world price level'};
M_.endo_names = cell(56,1);
M_.endo_names_tex = cell(56,1);
M_.endo_names_long = cell(56,1);
M_.endo_names(1) = {'y_gap'};
M_.endo_names_tex(1) = {'{\tilde{y}_t}'};
M_.endo_names_long(1) = {'Output gap'};
M_.endo_names(2) = {'pi_h'};
M_.endo_names_tex(2) = {'{\pi_{H,t}}'};
M_.endo_names_long(2) = {'domestic inflation'};
M_.endo_names(3) = {'y_nat'};
M_.endo_names_tex(3) = {'{y^{n}}'};
M_.endo_names_long(3) = {'natural output'};
M_.endo_names(4) = {'r_nat'};
M_.endo_names_tex(4) = {'{r^{n}}'};
M_.endo_names_long(4) = {'natural interest rate'};
M_.endo_names(5) = {'s_nat'};
M_.endo_names_tex(5) = {'{s^{n}}'};
M_.endo_names_long(5) = {'natural terms of trade'};
M_.endo_names(6) = {'y'};
M_.endo_names_tex(6) = {'{y}'};
M_.endo_names_long(6) = {'output'};
M_.endo_names(7) = {'s_gap'};
M_.endo_names_tex(7) = {'{\tilde{s}}'};
M_.endo_names_long(7) = {'terms of trade gap'};
M_.endo_names(8) = {'s'};
M_.endo_names_tex(8) = {'{s}'};
M_.endo_names_long(8) = {'terms of trade'};
M_.endo_names(9) = {'pi'};
M_.endo_names_tex(9) = {'{\pi}'};
M_.endo_names_long(9) = {'CPI inflation'};
M_.endo_names(10) = {'n'};
M_.endo_names_tex(10) = {'{n}'};
M_.endo_names_long(10) = {'employment'};
M_.endo_names(11) = {'r_real'};
M_.endo_names_tex(11) = {'{r^r}'};
M_.endo_names_long(11) = {'real interest rate'};
M_.endo_names(12) = {'w'};
M_.endo_names_tex(12) = {'{w}'};
M_.endo_names_long(12) = {'nominal wage'};
M_.endo_names(13) = {'nx'};
M_.endo_names_tex(13) = {'{nx}'};
M_.endo_names_long(13) = {'net exports in terms of domestic outout'};
M_.endo_names(14) = {'c'};
M_.endo_names_tex(14) = {'{c}'};
M_.endo_names_long(14) = {'consumption'};
M_.endo_names(15) = {'yhat'};
M_.endo_names_tex(15) = {'{\hat y}'};
M_.endo_names_long(15) = {'output deviation from steady state'};
M_.endo_names(16) = {'p_h'};
M_.endo_names_tex(16) = {'{p_H}'};
M_.endo_names_long(16) = {'domestic price level'};
M_.endo_names(17) = {'p'};
M_.endo_names_tex(17) = {'{p}'};
M_.endo_names_long(17) = {'CPI'};
M_.endo_names(18) = {'er'};
M_.endo_names_tex(18) = {'{e}'};
M_.endo_names_long(18) = {'Nominal exchange rate'};
M_.endo_names(19) = {'d_er'};
M_.endo_names_tex(19) = {'{\Delta e}'};
M_.endo_names_long(19) = {'Nominal exchange rate growth'};
M_.endo_names(20) = {'y_star'};
M_.endo_names_tex(20) = {'{y^*}'};
M_.endo_names_long(20) = {'world output'};
M_.endo_names(21) = {'a'};
M_.endo_names_tex(21) = {'{a}'};
M_.endo_names_long(21) = {'AR(1) technology shock process'};
M_.endo_names(22) = {'z'};
M_.endo_names_tex(22) = {'{z}'};
M_.endo_names_long(22) = {'AR(1) preference shock process'};
M_.endo_names(23) = {'wp'};
M_.endo_names_tex(23) = {'{wp}'};
M_.endo_names_long(23) = {'Real Wage'};
M_.endo_names(24) = {'y_gap_f'};
M_.endo_names_tex(24) = {'{\tilde{y^f}}'};
M_.endo_names_long(24) = {'output gap'};
M_.endo_names(25) = {'pi_h_f'};
M_.endo_names_tex(25) = {'{\pi^f_H}'};
M_.endo_names_long(25) = {'domestic inflation'};
M_.endo_names(26) = {'y_nat_f'};
M_.endo_names_tex(26) = {'{{y^f}^{n}}'};
M_.endo_names_long(26) = {'natural output'};
M_.endo_names(27) = {'r_nat_f'};
M_.endo_names_tex(27) = {'{{r^f}^{n}}'};
M_.endo_names_long(27) = {'natural interest rate'};
M_.endo_names(28) = {'s_nat_f'};
M_.endo_names_tex(28) = {'{{s^f}^{n}}'};
M_.endo_names_long(28) = {'natural terms of trade'};
M_.endo_names(29) = {'y_f'};
M_.endo_names_tex(29) = {'{y^f}'};
M_.endo_names_long(29) = {'output'};
M_.endo_names(30) = {'s_gap_f'};
M_.endo_names_tex(30) = {'{\tilde{s^f}}'};
M_.endo_names_long(30) = {'terms of trade gap'};
M_.endo_names(31) = {'s_f'};
M_.endo_names_tex(31) = {'{s^f}'};
M_.endo_names_long(31) = {'terms of trade'};
M_.endo_names(32) = {'pi_f'};
M_.endo_names_tex(32) = {'{\pi^f}'};
M_.endo_names_long(32) = {'CPI inflation'};
M_.endo_names(33) = {'n_f'};
M_.endo_names_tex(33) = {'{n^f}'};
M_.endo_names_long(33) = {'employment'};
M_.endo_names(34) = {'r_real_f'};
M_.endo_names_tex(34) = {'{r^r}'};
M_.endo_names_long(34) = {'real interest rate'};
M_.endo_names(35) = {'w_f'};
M_.endo_names_tex(35) = {'{w^f}'};
M_.endo_names_long(35) = {'nominal wage'};
M_.endo_names(36) = {'nx_f'};
M_.endo_names_tex(36) = {'{nx^f}'};
M_.endo_names_long(36) = {'net exports in terms of domestic outout'};
M_.endo_names(37) = {'c_f'};
M_.endo_names_tex(37) = {'{c^f}'};
M_.endo_names_long(37) = {'consumption'};
M_.endo_names(38) = {'yhat_f'};
M_.endo_names_tex(38) = {'{\hat y^f}'};
M_.endo_names_long(38) = {'output deviation from steady state'};
M_.endo_names(39) = {'p_h_f'};
M_.endo_names_tex(39) = {'{p^f_H}'};
M_.endo_names_long(39) = {'domestic price level'};
M_.endo_names(40) = {'p_f'};
M_.endo_names_tex(40) = {'{p^f}'};
M_.endo_names_long(40) = {'CPI'};
M_.endo_names(41) = {'er_f'};
M_.endo_names_tex(41) = {'{e^f}'};
M_.endo_names_long(41) = {'Nominal exchange rate'};
M_.endo_names(42) = {'d_er_f'};
M_.endo_names_tex(42) = {'{\Delta e^f}'};
M_.endo_names_long(42) = {'Nominal exchange rate growth'};
M_.endo_names(43) = {'a_f'};
M_.endo_names_tex(43) = {'{a^f}'};
M_.endo_names_long(43) = {'AR(1) technology shock process'};
M_.endo_names(44) = {'z_f'};
M_.endo_names_tex(44) = {'{z^f}'};
M_.endo_names_long(44) = {'AR(1) preference shock process'};
M_.endo_names(45) = {'wp_f'};
M_.endo_names_tex(45) = {'{wp^f}'};
M_.endo_names_long(45) = {'Real Wage'};
M_.endo_names(46) = {'g'};
M_.endo_names_tex(46) = {'{g}'};
M_.endo_names_long(46) = {'Government Spending'};
M_.endo_names(47) = {'tr'};
M_.endo_names_tex(47) = {'{TR}'};
M_.endo_names_long(47) = {'Tax Revenue'};
M_.endo_names(48) = {'g_f'};
M_.endo_names_tex(48) = {'{g^f}'};
M_.endo_names_long(48) = {'Government Spending'};
M_.endo_names(49) = {'tr_f'};
M_.endo_names_tex(49) = {'{TR^f}'};
M_.endo_names_long(49) = {'Tax Revenue'};
M_.endo_names(50) = {'b'};
M_.endo_names_tex(50) = {'b'};
M_.endo_names_long(50) = {'b'};
M_.endo_names(51) = {'b_f'};
M_.endo_names_tex(51) = {'b\_f'};
M_.endo_names_long(51) = {'b_f'};
M_.endo_names(52) = {'tau'};
M_.endo_names_tex(52) = {'{\tau_l}'};
M_.endo_names_long(52) = {'Labour Tax (Scotland)'};
M_.endo_names(53) = {'tau_f'};
M_.endo_names_tex(53) = {'{\tau^f_l}'};
M_.endo_names_long(53) = {'Labour Tax (rUK)'};
M_.endo_names(54) = {'nu_uk'};
M_.endo_names_tex(54) = {'{\nu}'};
M_.endo_names_long(54) = {'AR(1) monetary policy shock process'};
M_.endo_names(55) = {'interest_uk'};
M_.endo_names_tex(55) = {'{i^f}'};
M_.endo_names_long(55) = {'Interest Rate (UK)'};
M_.endo_names(56) = {'AUX_ENDO_LAG_19_1'};
M_.endo_names_tex(56) = {'AUX\_ENDO\_LAG\_19\_1'};
M_.endo_names_long(56) = {'AUX_ENDO_LAG_19_1'};
M_.endo_partitions = struct();
M_.param_names = cell(45,1);
M_.param_names_tex = cell(45,1);
M_.param_names_long = cell(45,1);
M_.param_names(1) = {'siggma'};
M_.param_names_tex(1) = {'{\sigma}'};
M_.param_names_long(1) = {'inverse EIS'};
M_.param_names(2) = {'betta'};
M_.param_names_tex(2) = {'{\beta}'};
M_.param_names_long(2) = {'discount factor'};
M_.param_names(3) = {'varphi'};
M_.param_names_tex(3) = {'{\varphi}'};
M_.param_names_long(3) = {'inverse Frisch elasticity'};
M_.param_names(4) = {'alppha'};
M_.param_names_tex(4) = {'{\alpha}'};
M_.param_names_long(4) = {'capital share'};
M_.param_names(5) = {'epsilon'};
M_.param_names_tex(5) = {'{\epsilon}'};
M_.param_names_long(5) = {'demand elasticity'};
M_.param_names(6) = {'theta'};
M_.param_names_tex(6) = {'{\theta}'};
M_.param_names_long(6) = {'Calvo parameter'};
M_.param_names(7) = {'upsilon'};
M_.param_names_tex(7) = {'{\upsilon}'};
M_.param_names_long(7) = {'openness parameter'};
M_.param_names(8) = {'eta'};
M_.param_names_tex(8) = {'{\eta}'};
M_.param_names_long(8) = {'substitutability foreign/domestic goods'};
M_.param_names(9) = {'rho_a'};
M_.param_names_tex(9) = {'{\rho_a}'};
M_.param_names_long(9) = {'autocorrelation technology shock'};
M_.param_names(10) = {'rho_nu'};
M_.param_names_tex(10) = {'{\rho_{\nu}}'};
M_.param_names_long(10) = {'autocorrelation monetary policy shock'};
M_.param_names(11) = {'rho_y_star'};
M_.param_names_tex(11) = {'{\rho_{y^*}}'};
M_.param_names_long(11) = {'autocorrelation world output growth shock'};
M_.param_names(12) = {'rho_z'};
M_.param_names_tex(12) = {'{\rho_{z}}'};
M_.param_names_long(12) = {'autocorrelation preference shock'};
M_.param_names(13) = {'siggma_f'};
M_.param_names_tex(13) = {'{\sigma}'};
M_.param_names_long(13) = {'inverse EIS'};
M_.param_names(14) = {'betta_f'};
M_.param_names_tex(14) = {'{\beta}'};
M_.param_names_long(14) = {'discount factor'};
M_.param_names(15) = {'varphi_f'};
M_.param_names_tex(15) = {'{\varphi}'};
M_.param_names_long(15) = {'inverse Frisch elasticity'};
M_.param_names(16) = {'alppha_f'};
M_.param_names_tex(16) = {'{\alpha}'};
M_.param_names_long(16) = {'capital share'};
M_.param_names(17) = {'epsilon_f'};
M_.param_names_tex(17) = {'{\epsilon}'};
M_.param_names_long(17) = {'demand elasticity'};
M_.param_names(18) = {'theta_f'};
M_.param_names_tex(18) = {'{\theta}'};
M_.param_names_long(18) = {'Calvo parameter'};
M_.param_names(19) = {'upsilon_f'};
M_.param_names_tex(19) = {'{\upsilon}'};
M_.param_names_long(19) = {'openness parameter'};
M_.param_names(20) = {'eta_f'};
M_.param_names_tex(20) = {'{\eta}'};
M_.param_names_long(20) = {'substitutability foreign/domestic goods'};
M_.param_names(21) = {'rho_a_f'};
M_.param_names_tex(21) = {'{\rho_a}'};
M_.param_names_long(21) = {'autocorrelation technology shock'};
M_.param_names(22) = {'rho_y_star_f'};
M_.param_names_tex(22) = {'{\rho_{y^*}}'};
M_.param_names_long(22) = {'autocorrelation world output growth shock'};
M_.param_names(23) = {'rho_z_f'};
M_.param_names_tex(23) = {'{\rho_{z}}'};
M_.param_names_long(23) = {'autocorrelation preference shock'};
M_.param_names(24) = {'rho_g'};
M_.param_names_tex(24) = {'{\rho_g}'};
M_.param_names_long(24) = {'AR(1) coefficient for Government spending (Scotland)'};
M_.param_names(25) = {'rho_g_f'};
M_.param_names_tex(25) = {'{\rho_g}'};
M_.param_names_long(25) = {'AR(1) coefficient for Government spending (rUK)'};
M_.param_names(26) = {'WN_T_SS'};
M_.param_names_tex(26) = {'{\frac{WN}{T}}'};
M_.param_names_long(26) = {'Pre-tax income/tax revenue ratio'};
M_.param_names(27) = {'WN_T_SS_f'};
M_.param_names_tex(27) = {'{\frac{W^fN^f}{T^f}}'};
M_.param_names_long(27) = {'Pre-tax income/tax revenue ratio'};
M_.param_names(28) = {'phi_b'};
M_.param_names_tex(28) = {'phi\_b'};
M_.param_names_long(28) = {'phi_b'};
M_.param_names(29) = {'phi_b_f'};
M_.param_names_tex(29) = {'phi\_b\_f'};
M_.param_names_long(29) = {'phi_b_f'};
M_.param_names(30) = {'phi_g'};
M_.param_names_tex(30) = {'phi\_g'};
M_.param_names_long(30) = {'phi_g'};
M_.param_names(31) = {'phi_g_f'};
M_.param_names_tex(31) = {'phi\_g\_f'};
M_.param_names_long(31) = {'phi_g_f'};
M_.param_names(32) = {'B_Y_SS'};
M_.param_names_tex(32) = {'B\_Y\_SS'};
M_.param_names_long(32) = {'B_Y_SS'};
M_.param_names(33) = {'TR_Y_SS'};
M_.param_names_tex(33) = {'TR\_Y\_SS'};
M_.param_names_long(33) = {'TR_Y_SS'};
M_.param_names(34) = {'B_Y_SS_f'};
M_.param_names_tex(34) = {'B\_Y\_SS\_f'};
M_.param_names_long(34) = {'B_Y_SS_f'};
M_.param_names(35) = {'TR_Y_SS_f'};
M_.param_names_tex(35) = {'TR\_Y\_SS\_f'};
M_.param_names_long(35) = {'TR_Y_SS_f'};
M_.param_names(36) = {'tau_ss'};
M_.param_names_tex(36) = {'{\tilde{\tau}}'};
M_.param_names_long(36) = {'Average labour tax rate (Scotland)'};
M_.param_names(37) = {'tau_ss_f'};
M_.param_names_tex(37) = {'{\tilde{\tau}}^f'};
M_.param_names_long(37) = {'Average labour tax rate (rUK)'};
M_.param_names(38) = {'pop'};
M_.param_names_tex(38) = {'{pop}'};
M_.param_names_long(38) = {'Scottish population share in the UK'};
M_.param_names(39) = {'phi_pi'};
M_.param_names_tex(39) = {'{\phi_{\pi}}'};
M_.param_names_long(39) = {'inflation feedback Taylor Rule'};
M_.param_names(40) = {'phi_y'};
M_.param_names_tex(40) = {'{\phi_{y}}'};
M_.param_names_long(40) = {'output feedback Taylor Rule'};
M_.param_names(41) = {'rho_i'};
M_.param_names_tex(41) = {'{\rho_i}'};
M_.param_names_long(41) = {'AR(1) coefficient for Taylor Rule'};
M_.param_names(42) = {'chi_pi'};
M_.param_names_tex(42) = {'{\chi_{\pi}}'};
M_.param_names_long(42) = {'rUK inflation impact on Scotland inflation parameter'};
M_.param_names(43) = {'chi_y'};
M_.param_names_tex(43) = {'{\rho_i}'};
M_.param_names_long(43) = {'rUK ouput gap impact on Scotland output gap parameter'};
M_.param_names(44) = {'chi_pi_ruk'};
M_.param_names_tex(44) = {'{\rho_i}'};
M_.param_names_long(44) = {'Scotland inflation impact on rUK inflation parameter'};
M_.param_names(45) = {'chi_y_ruk'};
M_.param_names_tex(45) = {'{\rho_i}'};
M_.param_names_long(45) = {'Scotland output gap impact on rUK output gap parameter'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 9;
M_.endo_nbr = 56;
M_.param_nbr = 45;
M_.orig_endo_nbr = 55;
M_.aux_vars(1).endo_index = 56;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 20;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(1).orig_expr = 'y_star(-1)';
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(9, 9);
M_.Correlation_matrix = eye(9, 9);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 55;
M_.eq_nbr = 56;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 2;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 2;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 2;
M_.lead_lag_incidence = [
 0 21 77;
 0 22 78;
 0 23 0;
 0 24 0;
 0 25 0;
 0 26 0;
 0 27 0;
 1 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 2 36 0;
 3 37 0;
 4 38 0;
 0 39 0;
 5 40 79;
 6 41 0;
 7 42 0;
 0 43 0;
 0 44 80;
 0 45 81;
 0 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 0 50 0;
 8 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 9 59 0;
 10 60 0;
 11 61 0;
 0 62 0;
 12 63 0;
 13 64 0;
 0 65 0;
 14 66 0;
 0 67 0;
 15 68 0;
 0 69 0;
 16 70 0;
 17 71 0;
 0 72 0;
 0 73 0;
 18 74 0;
 19 75 0;
 20 76 0;]';
M_.nstatic = 32;
M_.nfwrd   = 4;
M_.npred   = 19;
M_.nboth   = 1;
M_.nsfwrd   = 5;
M_.nspred   = 20;
M_.ndynamic   = 24;
M_.dynamic_tmp_nbr = [14; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'New Keynesian Phillips Curve (eq. 37)' ;
  2 , 'name' , 'Dynamic IS Curve (eq. 29)' ;
  3 , 'name' , 'Natural output (eq. 35)' ;
  4 , 'name' , 'Natural rate of interest (eq. 38)' ;
  5 , 'name' , 'Natural terms of trade (below eq. (35))' ;
  6 , 'name' , 'Terms of trade gap (middle p. 238)' ;
  7 , 'name' , 'Output' ;
  8 , 'name' , ' Terms of trade, p. 238' ;
  9 , 'name' , 'CPI inflation (13)' ;
  10 , 'name' , 'Production function (eq. 32)' ;
  11 , 'name' , 'Definition real interest rate' ;
  12 , 'name' , 'TFP shock, top of p. 233' ;
  13 , 'name' , 'Preference shock, top of p. 227' ;
  14 , 'name' , 'Output deviation from steady state' ;
  15 , 'name' , 'Domestic price level, p. 229' ;
  16 , 'name' , 'CPI definition' ;
  17 , 'name' , 'Nominal exchange rate' ;
  18 , 'name' , 'Definiion exchange rate growth' ;
  19 , 'name' , 'Real Wage' ;
  20 , 'name' , 'FOREIGN New Keynesian Phillips Curve (eq. 37)' ;
  21 , 'name' , 'FOREIGN Dynamic IS Curve (eq. 29)' ;
  22 , 'name' , 'FOREIGN Natural output (eq. 35)' ;
  23 , 'name' , 'FOREIGN Natural rate of interest (eq. 38)' ;
  24 , 'name' , 'FOREIGN Natural terms of trade (below eq. (35))' ;
  25 , 'name' , 'FOREIGN Terms of trade gap (middle p. 238)' ;
  26 , 'name' , 'FOREIGN Output' ;
  27 , 'name' , 'FOREIGN  Terms of trade, p. 238' ;
  28 , 'name' , 'FOREIGN CPI inflation (13)' ;
  29 , 'name' , 'FOREIGN Production function (eq. 32)' ;
  30 , 'name' , 'FOREIGN Definition real interest rate' ;
  31 , 'name' , 'FOREIGN TFP shock, top of p. 233' ;
  32 , 'name' , 'FOREIGN Preference shock, top of p. 227' ;
  33 , 'name' , 'FOREIGN Output deviation from steady state' ;
  34 , 'name' , 'FOREIGN Domestic price level, p. 229' ;
  35 , 'name' , 'FOREIGN CPI definition' ;
  36 , 'name' , 'FOREIGN Nominal exchange rate' ;
  37 , 'name' , 'FOREIGN Definition exchange rate growth' ;
  38 , 'name' , 'FOREIGN Real Wage' ;
  39 , 'name' , 'Taylor Rule' ;
  40 , 'name' , 'Monetary policy shock, below eq. (39)' ;
  41 , 'name' , 'World output growth shock' ;
  42 , 'name' , 'FOC wage, eq. (11)' ;
  43 , 'name' , '43' ;
  44 , 'name' , 'Net exports, eq. (31)' ;
  45 , 'name' , 'nx_f' ;
  46 , 'name' , 'Consumption determined by resource constraint, p. 236' ;
  47 , 'name' , '47' ;
  48 , 'name' , 'Tax Revenue' ;
  49 , 'name' , 'tr_f' ;
  50 , 'name' , '50' ;
  51 , 'name' , '51' ;
  52 , 'name' , '52' ;
  53 , 'name' , '53' ;
  54 , 'name' , 'Government spending' ;
  55 , 'name' , 'g_f' ;
};
M_.mapping.y_gap.eqidx = [1 2 6 7 21 ];
M_.mapping.pi_h.eqidx = [1 2 9 11 15 20 21 39 ];
M_.mapping.y_nat.eqidx = [3 5 7 ];
M_.mapping.r_nat.eqidx = [2 4 ];
M_.mapping.s_nat.eqidx = [5 8 ];
M_.mapping.y.eqidx = [7 10 14 46 ];
M_.mapping.s_gap.eqidx = [6 8 ];
M_.mapping.s.eqidx = [8 9 17 44 46 ];
M_.mapping.pi.eqidx = [9 16 ];
M_.mapping.n.eqidx = [10 42 48 ];
M_.mapping.r_real.eqidx = [11 ];
M_.mapping.w.eqidx = [19 ];
M_.mapping.nx.eqidx = [44 46 ];
M_.mapping.c.eqidx = [42 46 ];
M_.mapping.yhat.eqidx = [14 39 ];
M_.mapping.p_h.eqidx = [15 17 ];
M_.mapping.p.eqidx = [16 19 52 ];
M_.mapping.er.eqidx = [17 18 ];
M_.mapping.d_er.eqidx = [18 ];
M_.mapping.y_star.eqidx = [3 4 5 22 23 24 41 ];
M_.mapping.a.eqidx = [3 4 10 12 ];
M_.mapping.z.eqidx = [3 4 5 13 44 ];
M_.mapping.wp.eqidx = [19 42 48 ];
M_.mapping.y_gap_f.eqidx = [2 20 21 25 26 ];
M_.mapping.pi_h_f.eqidx = [1 2 20 21 28 30 34 39 ];
M_.mapping.y_nat_f.eqidx = [22 24 26 ];
M_.mapping.r_nat_f.eqidx = [21 23 ];
M_.mapping.s_nat_f.eqidx = [24 27 ];
M_.mapping.y_f.eqidx = [26 29 33 47 ];
M_.mapping.s_gap_f.eqidx = [25 27 ];
M_.mapping.s_f.eqidx = [27 28 36 45 47 ];
M_.mapping.pi_f.eqidx = [28 35 ];
M_.mapping.n_f.eqidx = [29 43 49 ];
M_.mapping.r_real_f.eqidx = [30 ];
M_.mapping.w_f.eqidx = [38 ];
M_.mapping.nx_f.eqidx = [45 47 ];
M_.mapping.c_f.eqidx = [43 47 ];
M_.mapping.yhat_f.eqidx = [33 39 ];
M_.mapping.p_h_f.eqidx = [34 36 ];
M_.mapping.p_f.eqidx = [35 38 50 51 53 ];
M_.mapping.er_f.eqidx = [36 37 ];
M_.mapping.d_er_f.eqidx = [37 ];
M_.mapping.a_f.eqidx = [22 23 29 31 ];
M_.mapping.z_f.eqidx = [22 23 24 32 45 ];
M_.mapping.wp_f.eqidx = [38 43 49 ];
M_.mapping.g.eqidx = [46 50 52 54 ];
M_.mapping.tr.eqidx = [48 50 ];
M_.mapping.g_f.eqidx = [47 51 53 55 ];
M_.mapping.tr_f.eqidx = [49 51 ];
M_.mapping.b.eqidx = [50 52 ];
M_.mapping.b_f.eqidx = [51 53 ];
M_.mapping.tau.eqidx = [42 48 ];
M_.mapping.tau_f.eqidx = [43 49 ];
M_.mapping.nu_uk.eqidx = [39 40 ];
M_.mapping.interest_uk.eqidx = [2 11 21 30 39 52 53 ];
M_.mapping.eps_a.eqidx = [12 ];
M_.mapping.eps_z.eqidx = [13 ];
M_.mapping.eps_a_f.eqidx = [31 ];
M_.mapping.eps_z_f.eqidx = [32 ];
M_.mapping.eps_nu_uk.eqidx = [40 ];
M_.mapping.eps_g.eqidx = [54 ];
M_.mapping.eps_g_f.eqidx = [55 ];
M_.mapping.eps_y_star.eqidx = [41 ];
M_.mapping.p_star.eqidx = [17 36 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [8 16 17 18 20 21 22 31 39 40 41 43 44 46 48 50 51 54 55 56 ];
M_.exo_names_orig_ord = [1:9];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(56, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(9, 1);
M_.params = NaN(45, 1);
M_.endo_trends = struct('deflator', cell(56, 1), 'log_deflator', cell(56, 1), 'growth_factor', cell(56, 1), 'log_growth_factor', cell(56, 1));
M_.NNZDerivatives = [204; 0; -1; ];
M_.static_tmp_nbr = [14; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(2) = 0.99;
betta = M_.params(2);
M_.params(1) = 1;
siggma = M_.params(1);
M_.params(3) = 6;
varphi = M_.params(3);
M_.params(4) = 0.25;
alppha = M_.params(4);
M_.params(5) = 6;
epsilon = M_.params(5);
M_.params(6) = 0.75;
theta = M_.params(6);
M_.params(7) = 0.6;
upsilon = M_.params(7);
M_.params(9) = 0.9;
rho_a = M_.params(9);
M_.params(11) = 0;
rho_y_star = M_.params(11);
M_.params(8) = 1;
eta = M_.params(8);
M_.params(12) = 0.5;
rho_z = M_.params(12);
M_.params(14) = M_.params(2);
betta_f = M_.params(14);
M_.params(13) = M_.params(1);
siggma_f = M_.params(13);
M_.params(15) = M_.params(3)-1;
varphi_f = M_.params(15);
M_.params(16) = M_.params(4);
alppha_f = M_.params(16);
M_.params(17) = M_.params(5);
epsilon_f = M_.params(17);
M_.params(18) = M_.params(6);
theta_f = M_.params(18);
M_.params(19) = M_.params(7);
upsilon_f = M_.params(19);
M_.params(21) = M_.params(9);
rho_a_f = M_.params(21);
M_.params(22) = M_.params(11);
rho_y_star_f = M_.params(22);
M_.params(20) = M_.params(8);
eta_f = M_.params(20);
M_.params(23) = M_.params(12);
rho_z_f = M_.params(23);
M_.params(38) = 0.08629;
pop = M_.params(38);
M_.params(10) = 0.5;
rho_nu = M_.params(10);
M_.params(41) = 0.5;
rho_i = M_.params(41);
M_.params(39) = 1.5;
phi_pi = M_.params(39);
M_.params(40) = 0.125;
phi_y = M_.params(40);
M_.params(42) = M_.params(38);
chi_pi = M_.params(42);
M_.params(43) = M_.params(38);
chi_y = M_.params(43);
M_.params(44) = 1-M_.params(38);
chi_pi_ruk = M_.params(44);
M_.params(45) = 1-M_.params(38);
chi_y_ruk = M_.params(45);
M_.params(24) = 0.5;
rho_g = M_.params(24);
M_.params(25) = M_.params(24);
rho_g_f = M_.params(25);
M_.params(26) = 0.18;
WN_T_SS = M_.params(26);
M_.params(27) = M_.params(26)+0.02;
WN_T_SS_f = M_.params(27);
M_.params(28) = 0.5;
phi_b = M_.params(28);
M_.params(30) = 0.5;
phi_g = M_.params(30);
M_.params(29) = M_.params(28);
phi_b_f = M_.params(29);
M_.params(31) = M_.params(30);
phi_g_f = M_.params(31);
M_.params(32) = 0.8;
B_Y_SS = M_.params(32);
M_.params(34) = M_.params(32);
B_Y_SS_f = M_.params(34);
M_.params(33) = 0.335;
TR_Y_SS = M_.params(33);
M_.params(35) = M_.params(33);
TR_Y_SS_f = M_.params(35);
M_.params(36) = 0.15;
tau_ss = M_.params(36);
M_.params(37) = M_.params(36)+0.05;
tau_ss_f = M_.params(37);
M_.params(36) = 0.15;
tau_ss = M_.params(36);
M_.params(37) = M_.params(36)+0.05;
tau_ss_f = M_.params(37);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(6, 6) = 0.0625;
resid(1);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.nocorr = true;
options_.nofunctions = true;
options_.nomoments = true;
options_.order = 2;
var_list_ = {'b';'r_real';'b_f';'g';'g_f';'tr';'tr_f';'tau';'tau_f';'c';'c_f';'y';'y_f';'w';'wp_f';'n';'n_f';'pi';'pi_f'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'oo_recursive_', '-append');
end
disp('Note: 2 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
