%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'dissertation';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(18,1);
M_.exo_names_tex = cell(18,1);
M_.exo_names_long = cell(18,1);
M_.exo_names(1) = {'eps_a'};
M_.exo_names_tex(1) = {'{\varepsilon^a}'};
M_.exo_names_long(1) = {'Technology shock'};
M_.exo_names(2) = {'eps_z'};
M_.exo_names_tex(2) = {'{\varepsilon^z}'};
M_.exo_names_long(2) = {'Preference shock'};
M_.exo_names(3) = {'eps_a_f'};
M_.exo_names_tex(3) = {'{\varepsilon^{f,a}}'};
M_.exo_names_long(3) = {'technology shock'};
M_.exo_names(4) = {'eps_z_f'};
M_.exo_names_tex(4) = {'{\varepsilon^{f,z}}'};
M_.exo_names_long(4) = {'preference shock'};
M_.exo_names(5) = {'eps_nu_uk'};
M_.exo_names_tex(5) = {'{\varepsilon^\nu}'};
M_.exo_names_long(5) = {'Monetary policy shock'};
M_.exo_names(6) = {'eps_g'};
M_.exo_names_tex(6) = {'{\varepsilon^{\tau}}'};
M_.exo_names_long(6) = {'Government Spending shock (Scotland)'};
M_.exo_names(7) = {'eps_g_f'};
M_.exo_names_tex(7) = {'{\varepsilon^{\tau,f}}'};
M_.exo_names_long(7) = {'Government Spending shock (rUK)'};
M_.exo_names(8) = {'eps_y_star'};
M_.exo_names_tex(8) = {'{\varepsilon^y}'};
M_.exo_names_long(8) = {'world output growth shock'};
M_.exo_names(9) = {'p_star'};
M_.exo_names_tex(9) = {'{p^*}'};
M_.exo_names_long(9) = {'world price level'};
M_.exo_names(10) = {'y_obs_me'};
M_.exo_names_tex(10) = {'{\varepsilon_y^{ME}}'};
M_.exo_names_long(10) = {'Observed Output ME'};
M_.exo_names(11) = {'c_obs_me'};
M_.exo_names_tex(11) = {'{\varepsilon_c^{ME}}'};
M_.exo_names_long(11) = {'Observed Consumption ME'};
M_.exo_names(12) = {'w_obs_me'};
M_.exo_names_tex(12) = {'{\varepsilon_w^{ME}}'};
M_.exo_names_long(12) = {'Observed Wage ME'};
M_.exo_names(13) = {'pi_obs_me'};
M_.exo_names_tex(13) = {'{\varepsilon_{\pi}^{ME}}'};
M_.exo_names_long(13) = {'Observed Inflation ME'};
M_.exo_names(14) = {'y_obs_ruk_me'};
M_.exo_names_tex(14) = {'{\varepsilon_y^{ME, RUK}}'};
M_.exo_names_long(14) = {'Observed Output ME (RUK)'};
M_.exo_names(15) = {'c_obs_ruk_me'};
M_.exo_names_tex(15) = {'{\varepsilon_c^{ME, RUK}}'};
M_.exo_names_long(15) = {'Observed Consumption ME (RUK)'};
M_.exo_names(16) = {'w_obs_ruk_me'};
M_.exo_names_tex(16) = {'{\varepsilon_w^{ME, RUK}}'};
M_.exo_names_long(16) = {'Observed Wage ME (RUK)'};
M_.exo_names(17) = {'pi_obs_ruk_me'};
M_.exo_names_tex(17) = {'{\varepsilon_{\pi}^{ME}}'};
M_.exo_names_long(17) = {'Observed Inflation ME (RUK)'};
M_.exo_names(18) = {'i_obs_me'};
M_.exo_names_tex(18) = {'{\varepsilon_i^{ME}}'};
M_.exo_names_long(18) = {'Observed Interest Rate ME (UK)'};
M_.endo_names = cell(70,1);
M_.endo_names_tex = cell(70,1);
M_.endo_names_long = cell(70,1);
M_.endo_names(1) = {'y_gap'};
M_.endo_names_tex(1) = {'{\tilde{y}_t}'};
M_.endo_names_long(1) = {'Output gap'};
M_.endo_names(2) = {'pi_h'};
M_.endo_names_tex(2) = {'{\pi_{H,t}}'};
M_.endo_names_long(2) = {'domestic inflation'};
M_.endo_names(3) = {'y_nat'};
M_.endo_names_tex(3) = {'{y^{n}}'};
M_.endo_names_long(3) = {'natural output'};
M_.endo_names(4) = {'r_nat'};
M_.endo_names_tex(4) = {'{r^{n}}'};
M_.endo_names_long(4) = {'natural interest rate'};
M_.endo_names(5) = {'s_nat'};
M_.endo_names_tex(5) = {'{s^{n}}'};
M_.endo_names_long(5) = {'natural terms of trade'};
M_.endo_names(6) = {'y'};
M_.endo_names_tex(6) = {'{y}'};
M_.endo_names_long(6) = {'output'};
M_.endo_names(7) = {'s_gap'};
M_.endo_names_tex(7) = {'{\tilde{s}}'};
M_.endo_names_long(7) = {'terms of trade gap'};
M_.endo_names(8) = {'s'};
M_.endo_names_tex(8) = {'{s}'};
M_.endo_names_long(8) = {'terms of trade'};
M_.endo_names(9) = {'pi'};
M_.endo_names_tex(9) = {'{\pi}'};
M_.endo_names_long(9) = {'CPI inflation'};
M_.endo_names(10) = {'n'};
M_.endo_names_tex(10) = {'{n}'};
M_.endo_names_long(10) = {'employment'};
M_.endo_names(11) = {'r_real'};
M_.endo_names_tex(11) = {'{r^r}'};
M_.endo_names_long(11) = {'real interest rate'};
M_.endo_names(12) = {'w'};
M_.endo_names_tex(12) = {'{w}'};
M_.endo_names_long(12) = {'nominal wage'};
M_.endo_names(13) = {'nx'};
M_.endo_names_tex(13) = {'{nx}'};
M_.endo_names_long(13) = {'net exports in terms of domestic outout'};
M_.endo_names(14) = {'c'};
M_.endo_names_tex(14) = {'{c}'};
M_.endo_names_long(14) = {'consumption'};
M_.endo_names(15) = {'yhat'};
M_.endo_names_tex(15) = {'{\hat y}'};
M_.endo_names_long(15) = {'output deviation from steady state'};
M_.endo_names(16) = {'p_h'};
M_.endo_names_tex(16) = {'{p_H}'};
M_.endo_names_long(16) = {'domestic price level'};
M_.endo_names(17) = {'p'};
M_.endo_names_tex(17) = {'{p}'};
M_.endo_names_long(17) = {'CPI'};
M_.endo_names(18) = {'er'};
M_.endo_names_tex(18) = {'{e}'};
M_.endo_names_long(18) = {'Nominal exchange rate'};
M_.endo_names(19) = {'d_er'};
M_.endo_names_tex(19) = {'{\Delta e}'};
M_.endo_names_long(19) = {'Nominal exchange rate growth'};
M_.endo_names(20) = {'y_star'};
M_.endo_names_tex(20) = {'{y^*}'};
M_.endo_names_long(20) = {'world output'};
M_.endo_names(21) = {'a'};
M_.endo_names_tex(21) = {'{a}'};
M_.endo_names_long(21) = {'AR(1) technology shock process'};
M_.endo_names(22) = {'z'};
M_.endo_names_tex(22) = {'{z}'};
M_.endo_names_long(22) = {'AR(1) preference shock process'};
M_.endo_names(23) = {'wp'};
M_.endo_names_tex(23) = {'{wp}'};
M_.endo_names_long(23) = {'Real Wage'};
M_.endo_names(24) = {'y_gap_f'};
M_.endo_names_tex(24) = {'{\tilde{y^f}}'};
M_.endo_names_long(24) = {'output gap'};
M_.endo_names(25) = {'pi_h_f'};
M_.endo_names_tex(25) = {'{\pi^f_H}'};
M_.endo_names_long(25) = {'domestic inflation'};
M_.endo_names(26) = {'y_nat_f'};
M_.endo_names_tex(26) = {'{{y^f}^{n}}'};
M_.endo_names_long(26) = {'natural output'};
M_.endo_names(27) = {'r_nat_f'};
M_.endo_names_tex(27) = {'{{r^f}^{n}}'};
M_.endo_names_long(27) = {'natural interest rate'};
M_.endo_names(28) = {'s_nat_f'};
M_.endo_names_tex(28) = {'{{s^f}^{n}}'};
M_.endo_names_long(28) = {'natural terms of trade'};
M_.endo_names(29) = {'y_f'};
M_.endo_names_tex(29) = {'{y^f}'};
M_.endo_names_long(29) = {'output'};
M_.endo_names(30) = {'s_gap_f'};
M_.endo_names_tex(30) = {'{\tilde{s^f}}'};
M_.endo_names_long(30) = {'terms of trade gap'};
M_.endo_names(31) = {'s_f'};
M_.endo_names_tex(31) = {'{s^f}'};
M_.endo_names_long(31) = {'terms of trade'};
M_.endo_names(32) = {'pi_f'};
M_.endo_names_tex(32) = {'{\pi^f}'};
M_.endo_names_long(32) = {'CPI inflation'};
M_.endo_names(33) = {'n_f'};
M_.endo_names_tex(33) = {'{n^f}'};
M_.endo_names_long(33) = {'employment'};
M_.endo_names(34) = {'r_real_f'};
M_.endo_names_tex(34) = {'{r^r}'};
M_.endo_names_long(34) = {'real interest rate'};
M_.endo_names(35) = {'w_f'};
M_.endo_names_tex(35) = {'{w^f}'};
M_.endo_names_long(35) = {'nominal wage'};
M_.endo_names(36) = {'nx_f'};
M_.endo_names_tex(36) = {'{nx^f}'};
M_.endo_names_long(36) = {'net exports in terms of domestic outout'};
M_.endo_names(37) = {'c_f'};
M_.endo_names_tex(37) = {'{c^f}'};
M_.endo_names_long(37) = {'consumption'};
M_.endo_names(38) = {'yhat_f'};
M_.endo_names_tex(38) = {'{\hat y^f}'};
M_.endo_names_long(38) = {'output deviation from steady state'};
M_.endo_names(39) = {'p_h_f'};
M_.endo_names_tex(39) = {'{p^f_H}'};
M_.endo_names_long(39) = {'domestic price level'};
M_.endo_names(40) = {'p_f'};
M_.endo_names_tex(40) = {'{p^f}'};
M_.endo_names_long(40) = {'CPI'};
M_.endo_names(41) = {'er_f'};
M_.endo_names_tex(41) = {'{e^f}'};
M_.endo_names_long(41) = {'Nominal exchange rate'};
M_.endo_names(42) = {'d_er_f'};
M_.endo_names_tex(42) = {'{\Delta e^f}'};
M_.endo_names_long(42) = {'Nominal exchange rate growth'};
M_.endo_names(43) = {'a_f'};
M_.endo_names_tex(43) = {'{a^f}'};
M_.endo_names_long(43) = {'AR(1) technology shock process'};
M_.endo_names(44) = {'z_f'};
M_.endo_names_tex(44) = {'{z^f}'};
M_.endo_names_long(44) = {'AR(1) preference shock process'};
M_.endo_names(45) = {'wp_f'};
M_.endo_names_tex(45) = {'{wp^f}'};
M_.endo_names_long(45) = {'Real Wage'};
M_.endo_names(46) = {'p_h_uk'};
M_.endo_names_tex(46) = {'p\_h\_uk'};
M_.endo_names_long(46) = {'p_h_uk'};
M_.endo_names(47) = {'g'};
M_.endo_names_tex(47) = {'{g}'};
M_.endo_names_long(47) = {'Government Spending'};
M_.endo_names(48) = {'tr'};
M_.endo_names_tex(48) = {'{TR}'};
M_.endo_names_long(48) = {'Tax Revenue'};
M_.endo_names(49) = {'g_f'};
M_.endo_names_tex(49) = {'{g^f}'};
M_.endo_names_long(49) = {'Government Spending'};
M_.endo_names(50) = {'tr_f'};
M_.endo_names_tex(50) = {'{TR^f}'};
M_.endo_names_long(50) = {'Tax Revenue'};
M_.endo_names(51) = {'b'};
M_.endo_names_tex(51) = {'b'};
M_.endo_names_long(51) = {'b'};
M_.endo_names(52) = {'b_f'};
M_.endo_names_tex(52) = {'b\_f'};
M_.endo_names_long(52) = {'b_f'};
M_.endo_names(53) = {'debt'};
M_.endo_names_tex(53) = {'debt'};
M_.endo_names_long(53) = {'debt'};
M_.endo_names(54) = {'debt_f'};
M_.endo_names_tex(54) = {'debt\_f'};
M_.endo_names_long(54) = {'debt_f'};
M_.endo_names(55) = {'tau'};
M_.endo_names_tex(55) = {'{\tau_l}'};
M_.endo_names_long(55) = {'Labour Tax (Scotland)'};
M_.endo_names(56) = {'tau_f'};
M_.endo_names_tex(56) = {'{\tau^f_l}'};
M_.endo_names_long(56) = {'Labour Tax (rUK)'};
M_.endo_names(57) = {'interest'};
M_.endo_names_tex(57) = {'{i}'};
M_.endo_names_long(57) = {'Interest Rate (Scotland)'};
M_.endo_names(58) = {'interest_f'};
M_.endo_names_tex(58) = {'{i^f}'};
M_.endo_names_long(58) = {'Interest Rate (rUK)'};
M_.endo_names(59) = {'interest_uk'};
M_.endo_names_tex(59) = {'{i^f}'};
M_.endo_names_long(59) = {'Interest Rate (UK)'};
M_.endo_names(60) = {'nu_uk'};
M_.endo_names_tex(60) = {'{\nu}'};
M_.endo_names_long(60) = {'AR(1) monetary policy shock process'};
M_.endo_names(61) = {'y_obs'};
M_.endo_names_tex(61) = {'{y^{OBS}}'};
M_.endo_names_long(61) = {'Observed Output'};
M_.endo_names(62) = {'c_obs'};
M_.endo_names_tex(62) = {'{c^{OBS}}'};
M_.endo_names_long(62) = {'Observed Consumption'};
M_.endo_names(63) = {'w_obs'};
M_.endo_names_tex(63) = {'{w^{OBS}}'};
M_.endo_names_long(63) = {'Observed Wage'};
M_.endo_names(64) = {'pi_obs'};
M_.endo_names_tex(64) = {'{\pi^{OBS}}'};
M_.endo_names_long(64) = {'Observed Inflation'};
M_.endo_names(65) = {'y_obs_ruk'};
M_.endo_names_tex(65) = {'{y^{OBS, ruk}}'};
M_.endo_names_long(65) = {'Observed Output (RUK)'};
M_.endo_names(66) = {'c_obs_ruk'};
M_.endo_names_tex(66) = {'{c^{OBS, ruk}}'};
M_.endo_names_long(66) = {'Observed Consumption (RUK)'};
M_.endo_names(67) = {'w_obs_ruk'};
M_.endo_names_tex(67) = {'{w^{OBS, ruk}}'};
M_.endo_names_long(67) = {'Observed Wage (RUK)'};
M_.endo_names(68) = {'pi_obs_ruk'};
M_.endo_names_tex(68) = {'{\pi^{OBS, ruk}}'};
M_.endo_names_long(68) = {'Observed Inflation (RUK)'};
M_.endo_names(69) = {'i_obs'};
M_.endo_names_tex(69) = {'{i^{OBS, uk}}'};
M_.endo_names_long(69) = {'Observed Interest Rate (UK)'};
M_.endo_names(70) = {'AUX_ENDO_LAG_19_1'};
M_.endo_names_tex(70) = {'AUX\_ENDO\_LAG\_19\_1'};
M_.endo_names_long(70) = {'AUX_ENDO_LAG_19_1'};
M_.endo_partitions = struct();
M_.param_names = cell(47,1);
M_.param_names_tex = cell(47,1);
M_.param_names_long = cell(47,1);
M_.param_names(1) = {'siggma'};
M_.param_names_tex(1) = {'{\sigma}'};
M_.param_names_long(1) = {'inverse EIS'};
M_.param_names(2) = {'betta'};
M_.param_names_tex(2) = {'{\beta}'};
M_.param_names_long(2) = {'discount factor'};
M_.param_names(3) = {'varphi'};
M_.param_names_tex(3) = {'{\varphi}'};
M_.param_names_long(3) = {'inverse Frisch elasticity'};
M_.param_names(4) = {'alppha'};
M_.param_names_tex(4) = {'{\alpha}'};
M_.param_names_long(4) = {'capital share'};
M_.param_names(5) = {'epsilon'};
M_.param_names_tex(5) = {'{\epsilon}'};
M_.param_names_long(5) = {'demand elasticity'};
M_.param_names(6) = {'theta'};
M_.param_names_tex(6) = {'{\theta}'};
M_.param_names_long(6) = {'Calvo parameter'};
M_.param_names(7) = {'upsilon'};
M_.param_names_tex(7) = {'{\upsilon}'};
M_.param_names_long(7) = {'openness parameter'};
M_.param_names(8) = {'eta'};
M_.param_names_tex(8) = {'{\eta}'};
M_.param_names_long(8) = {'substitutability foreign/domestic goods'};
M_.param_names(9) = {'rho_a'};
M_.param_names_tex(9) = {'{\rho_a}'};
M_.param_names_long(9) = {'autocorrelation technology shock'};
M_.param_names(10) = {'rho_nu'};
M_.param_names_tex(10) = {'{\rho_{\nu}}'};
M_.param_names_long(10) = {'autocorrelation monetary policy shock'};
M_.param_names(11) = {'rho_y_star'};
M_.param_names_tex(11) = {'{\rho_{y^*}}'};
M_.param_names_long(11) = {'autocorrelation world output growth shock'};
M_.param_names(12) = {'rho_z'};
M_.param_names_tex(12) = {'{\rho_{z}}'};
M_.param_names_long(12) = {'autocorrelation preference shock'};
M_.param_names(13) = {'siggma_f'};
M_.param_names_tex(13) = {'{\sigma}'};
M_.param_names_long(13) = {'inverse EIS'};
M_.param_names(14) = {'betta_f'};
M_.param_names_tex(14) = {'{\beta}'};
M_.param_names_long(14) = {'discount factor'};
M_.param_names(15) = {'varphi_f'};
M_.param_names_tex(15) = {'{\varphi}'};
M_.param_names_long(15) = {'inverse Frisch elasticity'};
M_.param_names(16) = {'alppha_f'};
M_.param_names_tex(16) = {'{\alpha}'};
M_.param_names_long(16) = {'capital share'};
M_.param_names(17) = {'epsilon_f'};
M_.param_names_tex(17) = {'{\epsilon}'};
M_.param_names_long(17) = {'demand elasticity'};
M_.param_names(18) = {'theta_f'};
M_.param_names_tex(18) = {'{\theta}'};
M_.param_names_long(18) = {'Calvo parameter'};
M_.param_names(19) = {'upsilon_f'};
M_.param_names_tex(19) = {'{\upsilon}'};
M_.param_names_long(19) = {'openness parameter'};
M_.param_names(20) = {'eta_f'};
M_.param_names_tex(20) = {'{\eta}'};
M_.param_names_long(20) = {'substitutability foreign/domestic goods'};
M_.param_names(21) = {'rho_a_f'};
M_.param_names_tex(21) = {'{\rho_a}'};
M_.param_names_long(21) = {'autocorrelation technology shock'};
M_.param_names(22) = {'rho_nu_f'};
M_.param_names_tex(22) = {'rho\_nu\_f'};
M_.param_names_long(22) = {'rho_nu_f'};
M_.param_names(23) = {'rho_y_star_f'};
M_.param_names_tex(23) = {'{\rho_{y^*}}'};
M_.param_names_long(23) = {'autocorrelation world output growth shock'};
M_.param_names(24) = {'rho_z_f'};
M_.param_names_tex(24) = {'{\rho_{z}}'};
M_.param_names_long(24) = {'autocorrelation preference shock'};
M_.param_names(25) = {'G_Y_SS'};
M_.param_names_tex(25) = {'G\_Y\_SS'};
M_.param_names_long(25) = {'G_Y_SS'};
M_.param_names(26) = {'G_Y_SS_f'};
M_.param_names_tex(26) = {'G\_Y\_SS\_f'};
M_.param_names_long(26) = {'G_Y_SS_f'};
M_.param_names(27) = {'C_Y_SS'};
M_.param_names_tex(27) = {'C\_Y\_SS'};
M_.param_names_long(27) = {'C_Y_SS'};
M_.param_names(28) = {'C_Y_SS_f'};
M_.param_names_tex(28) = {'C\_Y\_SS\_f'};
M_.param_names_long(28) = {'C_Y_SS_f'};
M_.param_names(29) = {'Y_C_SS'};
M_.param_names_tex(29) = {'Y\_C\_SS'};
M_.param_names_long(29) = {'Y_C_SS'};
M_.param_names(30) = {'Y_C_SS_f'};
M_.param_names_tex(30) = {'Y\_C\_SS\_f'};
M_.param_names_long(30) = {'Y_C_SS_f'};
M_.param_names(31) = {'G_C_SS'};
M_.param_names_tex(31) = {'G\_C\_SS'};
M_.param_names_long(31) = {'G_C_SS'};
M_.param_names(32) = {'G_C_SS_f'};
M_.param_names_tex(32) = {'G\_C\_SS\_f'};
M_.param_names_long(32) = {'G_C_SS_f'};
M_.param_names(33) = {'rho_g'};
M_.param_names_tex(33) = {'{\rho_g}'};
M_.param_names_long(33) = {'AR(1) coefficient for Government spending (Scotland)'};
M_.param_names(34) = {'rho_g_f'};
M_.param_names_tex(34) = {'{\rho_g}'};
M_.param_names_long(34) = {'AR(1) coefficient for Government spending (rUK)'};
M_.param_names(35) = {'phi_b'};
M_.param_names_tex(35) = {'phi\_b'};
M_.param_names_long(35) = {'phi_b'};
M_.param_names(36) = {'phi_b_f'};
M_.param_names_tex(36) = {'phi\_b\_f'};
M_.param_names_long(36) = {'phi_b_f'};
M_.param_names(37) = {'phi_g'};
M_.param_names_tex(37) = {'phi\_g'};
M_.param_names_long(37) = {'phi_g'};
M_.param_names(38) = {'phi_g_f'};
M_.param_names_tex(38) = {'phi\_g\_f'};
M_.param_names_long(38) = {'phi_g_f'};
M_.param_names(39) = {'tau_ss'};
M_.param_names_tex(39) = {'{\tilde{\tau}}'};
M_.param_names_long(39) = {'Average labour tax rate (Scotland)'};
M_.param_names(40) = {'tau_ss_f'};
M_.param_names_tex(40) = {'{\tilde{\tau}}^f'};
M_.param_names_long(40) = {'Average labour tax rate (rUK)'};
M_.param_names(41) = {'pop'};
M_.param_names_tex(41) = {'{pop}'};
M_.param_names_long(41) = {'Scottish population share in the UK'};
M_.param_names(42) = {'phi_pi'};
M_.param_names_tex(42) = {'{\phi_{\pi}}'};
M_.param_names_long(42) = {'inflation feedback Taylor Rule'};
M_.param_names(43) = {'phi_y'};
M_.param_names_tex(43) = {'{\phi_{y}}'};
M_.param_names_long(43) = {'output feedback Taylor Rule'};
M_.param_names(44) = {'rho_i'};
M_.param_names_tex(44) = {'{\rho_i}'};
M_.param_names_long(44) = {'AR(1) coefficient for Taylor Rule'};
M_.param_names(45) = {'phi_pi_f'};
M_.param_names_tex(45) = {'{\phi_{\pi}}'};
M_.param_names_long(45) = {'inflation feedback Taylor Rule'};
M_.param_names(46) = {'phi_y_f'};
M_.param_names_tex(46) = {'{\phi_{y}}'};
M_.param_names_long(46) = {'output feedback Taylor Rule'};
M_.param_names(47) = {'rho_i_f'};
M_.param_names_tex(47) = {'{\rho_i}'};
M_.param_names_long(47) = {'AR(1) coefficient for Taylor Rule'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 18;
M_.endo_nbr = 70;
M_.param_nbr = 47;
M_.orig_endo_nbr = 69;
M_.aux_vars(1).endo_index = 70;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 20;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(1).orig_expr = 'y_star(-1)';
M_.predetermined_variables = [ 51 52 ];
options_.varobs = cell(8, 1);
options_.varobs(1)  = {'y_obs'};
options_.varobs(2)  = {'c_obs'};
options_.varobs(3)  = {'w_obs'};
options_.varobs(4)  = {'y_obs_ruk'};
options_.varobs(5)  = {'c_obs_ruk'};
options_.varobs(6)  = {'w_obs_ruk'};
options_.varobs(7)  = {'pi_obs'};
options_.varobs(8)  = {'pi_obs_ruk'};
options_.varobs_id = [ 61 62 63 65 66 67 64 68  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(18, 18);
M_.Correlation_matrix = eye(18, 18);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 69;
M_.eq_nbr = 70;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 2;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 2;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 2;
M_.lead_lag_incidence = [
 0 27 97;
 0 28 98;
 0 29 0;
 0 30 0;
 0 31 0;
 1 32 0;
 0 33 0;
 2 34 0;
 0 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 3 40 0;
 0 41 0;
 4 42 0;
 5 43 0;
 6 44 0;
 0 45 0;
 7 46 99;
 8 47 0;
 9 48 0;
 10 49 0;
 0 50 100;
 0 51 101;
 0 52 0;
 0 53 0;
 0 54 0;
 11 55 0;
 0 56 0;
 12 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 13 63 0;
 0 64 0;
 14 65 0;
 15 66 0;
 16 67 0;
 0 68 0;
 17 69 0;
 18 70 0;
 19 71 0;
 0 72 0;
 20 73 0;
 0 74 0;
 21 75 0;
 0 76 0;
 22 77 0;
 23 78 0;
 0 79 0;
 0 80 0;
 0 81 102;
 0 82 103;
 0 83 0;
 0 84 0;
 24 85 0;
 25 86 0;
 0 87 0;
 0 88 0;
 0 89 0;
 0 90 0;
 0 91 0;
 0 92 0;
 0 93 0;
 0 94 0;
 0 95 0;
 26 96 0;]';
M_.nstatic = 38;
M_.nfwrd   = 6;
M_.npred   = 25;
M_.nboth   = 1;
M_.nsfwrd   = 7;
M_.nspred   = 26;
M_.ndynamic   = 32;
M_.dynamic_tmp_nbr = [16; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Taylor Rule' ;
  2 , 'name' , 'interest_f' ;
  3 , 'name' , 'Monetary policy shock' ;
  4 , 'name' , 'interest_uk' ;
  5 , 'name' , 'New Keynesian Phillips Curve' ;
  6 , 'name' , 'pi_h_f' ;
  7 , 'name' , 'Dynamic IS Curve' ;
  8 , 'name' , 'y_gap_f' ;
  9 , 'name' , 'Definition real interest rate' ;
  10 , 'name' , 'r_real_f' ;
  11 , 'name' , 'Natural output' ;
  12 , 'name' , 'y_nat_f' ;
  13 , 'name' , 'Natural rate of interest' ;
  14 , 'name' , 'r_nat_f' ;
  15 , 'name' , 'Natural terms of trade' ;
  16 , 'name' , 's_nat_f' ;
  17 , 'name' , 'World output growth shock' ;
  18 , 'name' , 'FOC wage' ;
  19 , 'name' , '19' ;
  20 , 'name' , 'Consumption determined by resource constraint' ;
  21 , 'name' , 'nx_f' ;
  22 , 'name' , 'nx' ;
  23 , 'name' , '23' ;
  24 , 'name' , 'Tax Revenue' ;
  25 , 'name' , 'tr_f' ;
  26 , 'name' , 'Debt Stabilising' ;
  27 , 'name' , '27' ;
  28 , 'name' , 'Bonds determined by budget constraint' ;
  29 , 'name' , 'b_f' ;
  30 , 'name' , 'Government spending' ;
  31 , 'name' , 'g_f' ;
  32 , 'name' , 'Debt' ;
  33 , 'name' , '33' ;
  34 , 'name' , 'Terms of trade gap' ;
  35 , 'name' , 's_gap_f' ;
  36 , 'name' , 'Output' ;
  37 , 'name' , '37' ;
  38 , 'name' , 'Terms of trade' ;
  39 , 'name' , '39' ;
  40 , 'name' , 'CPI Inflation' ;
  41 , 'name' , 'pi_f' ;
  42 , 'name' , 'Production function' ;
  43 , 'name' , 'y_f' ;
  44 , 'name' , 'TFP shock' ;
  45 , 'name' , 'a_f' ;
  46 , 'name' , 'Preference shock' ;
  47 , 'name' , 'z_f' ;
  48 , 'name' , 'Output deviation from steady state' ;
  49 , 'name' , 'yhat_f' ;
  50 , 'name' , 'Domestic price level' ;
  51 , 'name' , 'p_h_f' ;
  52 , 'name' , 'CPI definition' ;
  53 , 'name' , 'p_f' ;
  54 , 'name' , 'Nominal exchange rate' ;
  55 , 'name' , 's_f' ;
  56 , 'name' , 'Definition exchange rate growth' ;
  57 , 'name' , 'd_er_f' ;
  58 , 'name' , 'Inflation in the UK' ;
  59 , 'name' , 'Definition Real Wage' ;
  60 , 'name' , 'wp_f' ;
  61 , 'name' , 'y_obs' ;
  62 , 'name' , 'c_obs' ;
  63 , 'name' , 'w_obs' ;
  64 , 'name' , 'pi_obs' ;
  65 , 'name' , 'y_obs_ruk' ;
  66 , 'name' , 'c_obs_ruk' ;
  67 , 'name' , 'w_obs_ruk' ;
  68 , 'name' , 'pi_obs_ruk' ;
  69 , 'name' , 'i_obs' ;
};
M_.mapping.y_gap.eqidx = [5 7 34 36 ];
M_.mapping.pi_h.eqidx = [1 5 7 9 40 50 ];
M_.mapping.y_nat.eqidx = [11 15 36 ];
M_.mapping.r_nat.eqidx = [7 13 ];
M_.mapping.s_nat.eqidx = [15 38 ];
M_.mapping.y.eqidx = [20 36 42 48 61 ];
M_.mapping.s_gap.eqidx = [34 38 ];
M_.mapping.s.eqidx = [20 22 38 40 54 ];
M_.mapping.pi.eqidx = [40 52 64 ];
M_.mapping.n.eqidx = [18 24 42 ];
M_.mapping.r_real.eqidx = [9 ];
M_.mapping.w.eqidx = [59 ];
M_.mapping.nx.eqidx = [20 22 ];
M_.mapping.c.eqidx = [18 20 62 ];
M_.mapping.yhat.eqidx = [1 48 ];
M_.mapping.p_h.eqidx = [50 54 ];
M_.mapping.p.eqidx = [52 58 59 ];
M_.mapping.er.eqidx = [54 56 ];
M_.mapping.d_er.eqidx = [56 ];
M_.mapping.y_star.eqidx = [11 12 13 14 15 16 17 ];
M_.mapping.a.eqidx = [11 13 42 44 ];
M_.mapping.z.eqidx = [11 13 15 22 46 ];
M_.mapping.wp.eqidx = [18 24 59 63 ];
M_.mapping.y_gap_f.eqidx = [6 8 35 37 ];
M_.mapping.pi_h_f.eqidx = [2 6 8 10 41 51 ];
M_.mapping.y_nat_f.eqidx = [12 16 37 ];
M_.mapping.r_nat_f.eqidx = [8 14 ];
M_.mapping.s_nat_f.eqidx = [16 39 ];
M_.mapping.y_f.eqidx = [21 37 43 49 65 ];
M_.mapping.s_gap_f.eqidx = [35 39 ];
M_.mapping.s_f.eqidx = [21 23 39 41 55 ];
M_.mapping.pi_f.eqidx = [41 53 68 ];
M_.mapping.n_f.eqidx = [19 25 43 ];
M_.mapping.r_real_f.eqidx = [10 ];
M_.mapping.w_f.eqidx = [60 ];
M_.mapping.nx_f.eqidx = [21 23 ];
M_.mapping.c_f.eqidx = [19 21 66 ];
M_.mapping.yhat_f.eqidx = [2 49 ];
M_.mapping.p_h_f.eqidx = [51 55 ];
M_.mapping.p_f.eqidx = [53 58 60 ];
M_.mapping.er_f.eqidx = [55 57 ];
M_.mapping.d_er_f.eqidx = [57 ];
M_.mapping.a_f.eqidx = [12 14 43 45 ];
M_.mapping.z_f.eqidx = [12 14 16 23 47 ];
M_.mapping.wp_f.eqidx = [19 25 60 67 ];
M_.mapping.p_h_uk.eqidx = [58 ];
M_.mapping.g.eqidx = [11 13 15 20 26 28 30 32 ];
M_.mapping.tr.eqidx = [24 26 32 ];
M_.mapping.g_f.eqidx = [12 14 16 21 27 29 31 33 ];
M_.mapping.tr_f.eqidx = [25 27 33 ];
M_.mapping.b.eqidx = [26 28 ];
M_.mapping.b_f.eqidx = [27 29 ];
M_.mapping.debt.eqidx = [32 ];
M_.mapping.debt_f.eqidx = [33 ];
M_.mapping.tau.eqidx = [11 13 18 24 ];
M_.mapping.tau_f.eqidx = [12 14 19 25 ];
M_.mapping.interest.eqidx = [1 4 7 9 ];
M_.mapping.interest_f.eqidx = [2 4 8 10 ];
M_.mapping.interest_uk.eqidx = [4 69 ];
M_.mapping.nu_uk.eqidx = [1 2 3 ];
M_.mapping.y_obs.eqidx = [61 ];
M_.mapping.c_obs.eqidx = [62 ];
M_.mapping.w_obs.eqidx = [63 ];
M_.mapping.pi_obs.eqidx = [64 ];
M_.mapping.y_obs_ruk.eqidx = [65 ];
M_.mapping.c_obs_ruk.eqidx = [66 ];
M_.mapping.w_obs_ruk.eqidx = [67 ];
M_.mapping.pi_obs_ruk.eqidx = [68 ];
M_.mapping.i_obs.eqidx = [69 ];
M_.mapping.eps_a.eqidx = [44 ];
M_.mapping.eps_z.eqidx = [46 ];
M_.mapping.eps_a_f.eqidx = [45 ];
M_.mapping.eps_z_f.eqidx = [47 ];
M_.mapping.eps_nu_uk.eqidx = [3 ];
M_.mapping.eps_g.eqidx = [30 ];
M_.mapping.eps_g_f.eqidx = [31 ];
M_.mapping.eps_y_star.eqidx = [17 ];
M_.mapping.p_star.eqidx = [54 55 ];
M_.mapping.y_obs_me.eqidx = [61 ];
M_.mapping.c_obs_me.eqidx = [62 ];
M_.mapping.w_obs_me.eqidx = [63 ];
M_.mapping.pi_obs_me.eqidx = [64 ];
M_.mapping.y_obs_ruk_me.eqidx = [65 ];
M_.mapping.c_obs_ruk_me.eqidx = [66 ];
M_.mapping.w_obs_ruk_me.eqidx = [67 ];
M_.mapping.pi_obs_ruk_me.eqidx = [68 ];
M_.mapping.i_obs_me.eqidx = [69 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [6 8 14 16 17 18 20 21 22 23 29 31 37 39 40 41 43 44 45 47 49 51 52 59 60 70 ];
M_.exo_names_orig_ord = [1:18];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(70, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(18, 1);
M_.params = NaN(47, 1);
M_.endo_trends = struct('deflator', cell(70, 1), 'log_deflator', cell(70, 1), 'growth_factor', cell(70, 1), 'log_growth_factor', cell(70, 1));
M_.NNZDerivatives = [251; 0; -1; ];
M_.static_tmp_nbr = [16; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(2) = 0.99;
betta = M_.params(2);
M_.params(1) = 1;
siggma = M_.params(1);
M_.params(3) = 6;
varphi = M_.params(3);
M_.params(4) = 0.3333333333333333;
alppha = M_.params(4);
M_.params(5) = 6;
epsilon = M_.params(5);
M_.params(6) = 0.75;
theta = M_.params(6);
M_.params(7) = 0.6;
upsilon = M_.params(7);
M_.params(9) = 0.5;
rho_a = M_.params(9);
M_.params(11) = 0.5;
rho_y_star = M_.params(11);
M_.params(8) = 1;
eta = M_.params(8);
M_.params(12) = 0.5;
rho_z = M_.params(12);
M_.params(14) = M_.params(2);
betta_f = M_.params(14);
M_.params(13) = M_.params(1);
siggma_f = M_.params(13);
M_.params(15) = M_.params(3);
varphi_f = M_.params(15);
M_.params(16) = M_.params(4);
alppha_f = M_.params(16);
M_.params(17) = M_.params(5);
epsilon_f = M_.params(17);
M_.params(18) = M_.params(6);
theta_f = M_.params(18);
M_.params(19) = M_.params(7);
upsilon_f = M_.params(19);
M_.params(21) = M_.params(9);
rho_a_f = M_.params(21);
M_.params(23) = M_.params(11);
rho_y_star_f = M_.params(23);
M_.params(20) = M_.params(8);
eta_f = M_.params(20);
M_.params(24) = M_.params(12);
rho_z_f = M_.params(24);
M_.params(41) = 0.08629;
pop = M_.params(41);
M_.params(10) = 0.5;
rho_nu = M_.params(10);
M_.params(44) = 0;
rho_i = M_.params(44);
M_.params(42) = 1.5;
phi_pi = M_.params(42);
M_.params(43) = 0.125;
phi_y = M_.params(43);
M_.params(22) = M_.params(10);
rho_nu_f = M_.params(22);
M_.params(47) = M_.params(44);
rho_i_f = M_.params(47);
M_.params(45) = M_.params(42);
phi_pi_f = M_.params(45);
M_.params(46) = M_.params(43);
phi_y_f = M_.params(46);
M_.params(25) = 0.2;
G_Y_SS = M_.params(25);
M_.params(26) = M_.params(25);
G_Y_SS_f = M_.params(26);
M_.params(27) = 1-M_.params(25);
C_Y_SS = M_.params(27);
M_.params(28) = 1-M_.params(26);
C_Y_SS_f = M_.params(28);
M_.params(29) = 1/M_.params(27);
Y_C_SS = M_.params(29);
M_.params(30) = 1/M_.params(28);
Y_C_SS_f = M_.params(30);
M_.params(31) = M_.params(29)-1;
G_C_SS = M_.params(31);
M_.params(32) = M_.params(30)-1;
G_C_SS_f = M_.params(32);
M_.params(33) = 0.9;
rho_g = M_.params(33);
M_.params(34) = M_.params(33);
rho_g_f = M_.params(34);
M_.params(35) = 0.33;
phi_b = M_.params(35);
M_.params(37) = 0.10;
phi_g = M_.params(37);
M_.params(36) = M_.params(35);
phi_b_f = M_.params(36);
M_.params(38) = M_.params(37);
phi_g_f = M_.params(38);
M_.params(39) = 0.1;
tau_ss = M_.params(39);
M_.params(40) = M_.params(39);
tau_ss_f = M_.params(40);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0.0625;
M_.Sigma_e(2, 2) = 0.0625;
M_.Sigma_e(3, 3) = 0.0625;
M_.Sigma_e(4, 4) = 0.0625;
M_.Sigma_e(5, 5) = 0.0625;
M_.Sigma_e(8, 8) = 0.0625;
M_.Sigma_e(9, 9) = 0.0625;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.var_exo = [estim_params_.var_exo; 10, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 13, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 14, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 17, NaN, (-Inf), Inf, 4, 0.01, 2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 35, NaN, (-Inf), Inf, 1, 0.30, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 37, NaN, (-Inf), Inf, 1, 0.1, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 36, NaN, (-Inf), Inf, 1, 0.30, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 38, NaN, (-Inf), Inf, 1, 0.1, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 33, NaN, (-Inf), Inf, 1, 0.9, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 34, NaN, (-Inf), Inf, 1, 0.9, 0.05, NaN, NaN, NaN ];
options_.diffuse_filter = true;
options_.logdata = true;
options_.mh_jscale = 0.5;
options_.mh_nblck = 1;
options_.mh_replic = 20000;
options_.smoother = true;
options_.datafile = 'DynareData';
options_.order = 1;
options_.steadystate.nocheck = true;
var_list_ = {};
oo_recursive_=dynare_estimation(var_list_);
resid(1);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 30;
options_.order = 2;
var_list_ = {'nx';'nx_f';'y_star';'interest';'interest_f';'interest_uk';'s';'s_f';'s_nat';'s_nat_f';'debt';'debt_f';'b';'b_f';'g';'g_f';'tr';'tr_f';'tau';'tau_f';'c';'c_f';'y';'y_f';'wp';'wp_f';'n';'n_f';'p_h';'p_h_f';'pi_h';'pi_h_f';'p';'p_f';'w';'w_f';'pi';'pi_f'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'dissertation_results.mat'], 'oo_recursive_', '-append');
end
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
