%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'Model_Loes';
M_.dynare_version = '5.3';
oo_.dynare_version = '5.3';
options_.dynare_version = '5.3';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(15,1);
M_.exo_names_tex = cell(15,1);
M_.exo_names_long = cell(15,1);
M_.exo_names(1) = {'u_a_D_i'};
M_.exo_names_tex(1) = {'u\_a\_D\_i'};
M_.exo_names_long(1) = {'u_a_D_i'};
M_.exo_names(2) = {'u_a_D_j'};
M_.exo_names_tex(2) = {'u\_a\_D\_j'};
M_.exo_names_long(2) = {'u_a_D_j'};
M_.exo_names(3) = {'u_a_N_i'};
M_.exo_names_tex(3) = {'u\_a\_N\_i'};
M_.exo_names_long(3) = {'u_a_N_i'};
M_.exo_names(4) = {'u_a_N_j'};
M_.exo_names_tex(4) = {'u\_a\_N\_j'};
M_.exo_names_long(4) = {'u_a_N_j'};
M_.exo_names(5) = {'u_C_i'};
M_.exo_names_tex(5) = {'u\_C\_i'};
M_.exo_names_long(5) = {'u_C_i'};
M_.exo_names(6) = {'u_C_j'};
M_.exo_names_tex(6) = {'u\_C\_j'};
M_.exo_names_long(6) = {'u_C_j'};
M_.exo_names(7) = {'u_L_i'};
M_.exo_names_tex(7) = {'u\_L\_i'};
M_.exo_names_long(7) = {'u_L_i'};
M_.exo_names(8) = {'u_L_j'};
M_.exo_names_tex(8) = {'u\_L\_j'};
M_.exo_names_long(8) = {'u_L_j'};
M_.exo_names(9) = {'u_I_i'};
M_.exo_names_tex(9) = {'u\_I\_i'};
M_.exo_names_long(9) = {'u_I_i'};
M_.exo_names(10) = {'u_I_j'};
M_.exo_names_tex(10) = {'u\_I\_j'};
M_.exo_names_long(10) = {'u_I_j'};
M_.exo_names(11) = {'u_G_i'};
M_.exo_names_tex(11) = {'u\_G\_i'};
M_.exo_names_long(11) = {'u_G_i'};
M_.exo_names(12) = {'u_G_j'};
M_.exo_names_tex(12) = {'u\_G\_j'};
M_.exo_names_long(12) = {'u_G_j'};
M_.exo_names(13) = {'u_T_i'};
M_.exo_names_tex(13) = {'u\_T\_i'};
M_.exo_names_long(13) = {'u_T_i'};
M_.exo_names(14) = {'u_T_j'};
M_.exo_names_tex(14) = {'u\_T\_j'};
M_.exo_names_long(14) = {'u_T_j'};
M_.exo_names(15) = {'u_R'};
M_.exo_names_tex(15) = {'u\_R'};
M_.exo_names_long(15) = {'u_R'};
M_.endo_names = cell(64,1);
M_.endo_names_tex = cell(64,1);
M_.endo_names_long = cell(64,1);
M_.endo_names(1) = {'y_i'};
M_.endo_names_tex(1) = {'y\_i'};
M_.endo_names_long(1) = {'y_i'};
M_.endo_names(2) = {'y_j'};
M_.endo_names_tex(2) = {'y\_j'};
M_.endo_names_long(2) = {'y_j'};
M_.endo_names(3) = {'y_D_i'};
M_.endo_names_tex(3) = {'y\_D\_i'};
M_.endo_names_long(3) = {'y_D_i'};
M_.endo_names(4) = {'y_D_j'};
M_.endo_names_tex(4) = {'y\_D\_j'};
M_.endo_names_long(4) = {'y_D_j'};
M_.endo_names(5) = {'y_N_i'};
M_.endo_names_tex(5) = {'y\_N\_i'};
M_.endo_names_long(5) = {'y_N_i'};
M_.endo_names(6) = {'y_N_j'};
M_.endo_names_tex(6) = {'y\_N\_j'};
M_.endo_names_long(6) = {'y_N_j'};
M_.endo_names(7) = {'c_i'};
M_.endo_names_tex(7) = {'c\_i'};
M_.endo_names_long(7) = {'c_i'};
M_.endo_names(8) = {'c_j'};
M_.endo_names_tex(8) = {'c\_j'};
M_.endo_names_long(8) = {'c_j'};
M_.endo_names(9) = {'x_i'};
M_.endo_names_tex(9) = {'x\_i'};
M_.endo_names_long(9) = {'x_i'};
M_.endo_names(10) = {'x_j'};
M_.endo_names_tex(10) = {'x\_j'};
M_.endo_names_long(10) = {'x_j'};
M_.endo_names(11) = {'i_i'};
M_.endo_names_tex(11) = {'i\_i'};
M_.endo_names_long(11) = {'i_i'};
M_.endo_names(12) = {'i_j'};
M_.endo_names_tex(12) = {'i\_j'};
M_.endo_names_long(12) = {'i_j'};
M_.endo_names(13) = {'g_i'};
M_.endo_names_tex(13) = {'g\_i'};
M_.endo_names_long(13) = {'g_i'};
M_.endo_names(14) = {'g_j'};
M_.endo_names_tex(14) = {'g\_j'};
M_.endo_names_long(14) = {'g_j'};
M_.endo_names(15) = {'tax_i'};
M_.endo_names_tex(15) = {'tax\_i'};
M_.endo_names_long(15) = {'tax_i'};
M_.endo_names(16) = {'tax_j'};
M_.endo_names_tex(16) = {'tax\_j'};
M_.endo_names_long(16) = {'tax_j'};
M_.endo_names(17) = {'pi_C_i'};
M_.endo_names_tex(17) = {'pi\_C\_i'};
M_.endo_names_long(17) = {'pi_C_i'};
M_.endo_names(18) = {'pi_C_j'};
M_.endo_names_tex(18) = {'pi\_C\_j'};
M_.endo_names_long(18) = {'pi_C_j'};
M_.endo_names(19) = {'k_i'};
M_.endo_names_tex(19) = {'k\_i'};
M_.endo_names_long(19) = {'k_i'};
M_.endo_names(20) = {'k_j'};
M_.endo_names_tex(20) = {'k\_j'};
M_.endo_names_long(20) = {'k_j'};
M_.endo_names(21) = {'r_K_i'};
M_.endo_names_tex(21) = {'r\_K\_i'};
M_.endo_names_long(21) = {'r_K_i'};
M_.endo_names(22) = {'r_K_j'};
M_.endo_names_tex(22) = {'r\_K\_j'};
M_.endo_names_long(22) = {'r_K_j'};
M_.endo_names(23) = {'w_i'};
M_.endo_names_tex(23) = {'w\_i'};
M_.endo_names_long(23) = {'w_i'};
M_.endo_names(24) = {'w_j'};
M_.endo_names_tex(24) = {'w\_j'};
M_.endo_names_long(24) = {'w_j'};
M_.endo_names(25) = {'l_i'};
M_.endo_names_tex(25) = {'l\_i'};
M_.endo_names_long(25) = {'l_i'};
M_.endo_names(26) = {'l_j'};
M_.endo_names_tex(26) = {'l\_j'};
M_.endo_names_long(26) = {'l_j'};
M_.endo_names(27) = {'q_T_i'};
M_.endo_names_tex(27) = {'q\_T\_i'};
M_.endo_names_long(27) = {'q_T_i'};
M_.endo_names(28) = {'q_T_j'};
M_.endo_names_tex(28) = {'q\_T\_j'};
M_.endo_names_long(28) = {'q_T_j'};
M_.endo_names(29) = {'MRS_i'};
M_.endo_names_tex(29) = {'MRS\_i'};
M_.endo_names_long(29) = {'MRS_i'};
M_.endo_names(30) = {'MRS_j'};
M_.endo_names_tex(30) = {'MRS\_j'};
M_.endo_names_long(30) = {'MRS_j'};
M_.endo_names(31) = {'pi_D_i'};
M_.endo_names_tex(31) = {'pi\_D\_i'};
M_.endo_names_long(31) = {'pi_D_i'};
M_.endo_names(32) = {'pi_D_j'};
M_.endo_names_tex(32) = {'pi\_D\_j'};
M_.endo_names_long(32) = {'pi_D_j'};
M_.endo_names(33) = {'pi_N_i'};
M_.endo_names_tex(33) = {'pi\_N\_i'};
M_.endo_names_long(33) = {'pi_N_i'};
M_.endo_names(34) = {'pi_N_j'};
M_.endo_names_tex(34) = {'pi\_N\_j'};
M_.endo_names_long(34) = {'pi_N_j'};
M_.endo_names(35) = {'MC_D_i'};
M_.endo_names_tex(35) = {'MC\_D\_i'};
M_.endo_names_long(35) = {'MC_D_i'};
M_.endo_names(36) = {'MC_D_j'};
M_.endo_names_tex(36) = {'MC\_D\_j'};
M_.endo_names_long(36) = {'MC_D_j'};
M_.endo_names(37) = {'MC_N_i'};
M_.endo_names_tex(37) = {'MC\_N\_i'};
M_.endo_names_long(37) = {'MC_N_i'};
M_.endo_names(38) = {'MC_N_j'};
M_.endo_names_tex(38) = {'MC\_N\_j'};
M_.endo_names_long(38) = {'MC_N_j'};
M_.endo_names(39) = {'pi_T_i'};
M_.endo_names_tex(39) = {'pi\_T\_i'};
M_.endo_names_long(39) = {'pi_T_i'};
M_.endo_names(40) = {'pi_T_j'};
M_.endo_names_tex(40) = {'pi\_T\_j'};
M_.endo_names_long(40) = {'pi_T_j'};
M_.endo_names(41) = {'t'};
M_.endo_names_tex(41) = {'t'};
M_.endo_names_long(41) = {'t'};
M_.endo_names(42) = {'r'};
M_.endo_names_tex(42) = {'r'};
M_.endo_names_long(42) = {'r'};
M_.endo_names(43) = {'r_j'};
M_.endo_names_tex(43) = {'r\_j'};
M_.endo_names_long(43) = {'r_j'};
M_.endo_names(44) = {'q'};
M_.endo_names_tex(44) = {'q'};
M_.endo_names_long(44) = {'q'};
M_.endo_names(45) = {'y_EMU'};
M_.endo_names_tex(45) = {'y\_EMU'};
M_.endo_names_long(45) = {'y_EMU'};
M_.endo_names(46) = {'pi_C_EMU'};
M_.endo_names_tex(46) = {'pi\_C\_EMU'};
M_.endo_names_long(46) = {'pi_C_EMU'};
M_.endo_names(47) = {'tr_i'};
M_.endo_names_tex(47) = {'tr\_i'};
M_.endo_names_long(47) = {'tr_i'};
M_.endo_names(48) = {'tr_j'};
M_.endo_names_tex(48) = {'tr\_j'};
M_.endo_names_long(48) = {'tr_j'};
M_.endo_names(49) = {'d_i'};
M_.endo_names_tex(49) = {'d\_i'};
M_.endo_names_long(49) = {'d_i'};
M_.endo_names(50) = {'d_j'};
M_.endo_names_tex(50) = {'d\_j'};
M_.endo_names_long(50) = {'d_j'};
M_.endo_names(51) = {'tauC_i'};
M_.endo_names_tex(51) = {'tauC\_i'};
M_.endo_names_long(51) = {'tauC_i'};
M_.endo_names(52) = {'tauC_j'};
M_.endo_names_tex(52) = {'tauC\_j'};
M_.endo_names_long(52) = {'tauC_j'};
M_.endo_names(53) = {'tauK_i'};
M_.endo_names_tex(53) = {'tauK\_i'};
M_.endo_names_long(53) = {'tauK_i'};
M_.endo_names(54) = {'tauK_j'};
M_.endo_names_tex(54) = {'tauK\_j'};
M_.endo_names_long(54) = {'tauK_j'};
M_.endo_names(55) = {'a_D_i'};
M_.endo_names_tex(55) = {'a\_D\_i'};
M_.endo_names_long(55) = {'a_D_i'};
M_.endo_names(56) = {'a_D_j'};
M_.endo_names_tex(56) = {'a\_D\_j'};
M_.endo_names_long(56) = {'a_D_j'};
M_.endo_names(57) = {'a_N_i'};
M_.endo_names_tex(57) = {'a\_N\_i'};
M_.endo_names_long(57) = {'a_N_i'};
M_.endo_names(58) = {'a_N_j'};
M_.endo_names_tex(58) = {'a\_N\_j'};
M_.endo_names_long(58) = {'a_N_j'};
M_.endo_names(59) = {'epsilon_C_i'};
M_.endo_names_tex(59) = {'epsilon\_C\_i'};
M_.endo_names_long(59) = {'epsilon_C_i'};
M_.endo_names(60) = {'epsilon_C_j'};
M_.endo_names_tex(60) = {'epsilon\_C\_j'};
M_.endo_names_long(60) = {'epsilon_C_j'};
M_.endo_names(61) = {'epsilon_L_i'};
M_.endo_names_tex(61) = {'epsilon\_L\_i'};
M_.endo_names_long(61) = {'epsilon_L_i'};
M_.endo_names(62) = {'epsilon_L_j'};
M_.endo_names_tex(62) = {'epsilon\_L\_j'};
M_.endo_names_long(62) = {'epsilon_L_j'};
M_.endo_names(63) = {'epsilon_I_i'};
M_.endo_names_tex(63) = {'epsilon\_I\_i'};
M_.endo_names_long(63) = {'epsilon_I_i'};
M_.endo_names(64) = {'epsilon_I_j'};
M_.endo_names_tex(64) = {'epsilon\_I\_j'};
M_.endo_names_long(64) = {'epsilon_I_j'};
M_.endo_partitions = struct();
M_.param_names = cell(97,1);
M_.param_names_tex = cell(97,1);
M_.param_names_long = cell(97,1);
M_.param_names(1) = {'sigma'};
M_.param_names_tex(1) = {'sigma'};
M_.param_names_long(1) = {'sigma'};
M_.param_names(2) = {'phi'};
M_.param_names_tex(2) = {'phi'};
M_.param_names_long(2) = {'phi'};
M_.param_names(3) = {'beta'};
M_.param_names_tex(3) = {'beta'};
M_.param_names_long(3) = {'beta'};
M_.param_names(4) = {'gammaC'};
M_.param_names_tex(4) = {'gammaC'};
M_.param_names_long(4) = {'gammaC'};
M_.param_names(5) = {'alpha'};
M_.param_names_tex(5) = {'alpha'};
M_.param_names_long(5) = {'alpha'};
M_.param_names(6) = {'gammaI'};
M_.param_names_tex(6) = {'gammaI'};
M_.param_names_long(6) = {'gammaI'};
M_.param_names(7) = {'delta'};
M_.param_names_tex(7) = {'delta'};
M_.param_names_long(7) = {'delta'};
M_.param_names(8) = {'S'};
M_.param_names_tex(8) = {'S'};
M_.param_names_long(8) = {'S'};
M_.param_names(9) = {'eta'};
M_.param_names_tex(9) = {'eta'};
M_.param_names_long(9) = {'eta'};
M_.param_names(10) = {'deltaW'};
M_.param_names_tex(10) = {'deltaW'};
M_.param_names_long(10) = {'deltaW'};
M_.param_names(11) = {'thetaW'};
M_.param_names_tex(11) = {'thetaW'};
M_.param_names_long(11) = {'thetaW'};
M_.param_names(12) = {'deltaD'};
M_.param_names_tex(12) = {'deltaD'};
M_.param_names_long(12) = {'deltaD'};
M_.param_names(13) = {'thetaD'};
M_.param_names_tex(13) = {'thetaD'};
M_.param_names_long(13) = {'thetaD'};
M_.param_names(14) = {'deltaN'};
M_.param_names_tex(14) = {'deltaN'};
M_.param_names_long(14) = {'deltaN'};
M_.param_names(15) = {'thetaN'};
M_.param_names_tex(15) = {'thetaN'};
M_.param_names_long(15) = {'thetaN'};
M_.param_names(16) = {'h'};
M_.param_names_tex(16) = {'h'};
M_.param_names_long(16) = {'h'};
M_.param_names(17) = {'phiW'};
M_.param_names_tex(17) = {'phiW'};
M_.param_names_long(17) = {'phiW'};
M_.param_names(18) = {'rhotau'};
M_.param_names_tex(18) = {'rhotau'};
M_.param_names_long(18) = {'rhotau'};
M_.param_names(19) = {'rhodebt'};
M_.param_names_tex(19) = {'rhodebt'};
M_.param_names_long(19) = {'rhodebt'};
M_.param_names(20) = {'sigma_j'};
M_.param_names_tex(20) = {'sigma\_j'};
M_.param_names_long(20) = {'sigma_j'};
M_.param_names(21) = {'phi_j'};
M_.param_names_tex(21) = {'phi\_j'};
M_.param_names_long(21) = {'phi_j'};
M_.param_names(22) = {'beta_j'};
M_.param_names_tex(22) = {'beta\_j'};
M_.param_names_long(22) = {'beta_j'};
M_.param_names(23) = {'gammaC_j'};
M_.param_names_tex(23) = {'gammaC\_j'};
M_.param_names_long(23) = {'gammaC_j'};
M_.param_names(24) = {'alpha_j'};
M_.param_names_tex(24) = {'alpha\_j'};
M_.param_names_long(24) = {'alpha_j'};
M_.param_names(25) = {'gammaI_j'};
M_.param_names_tex(25) = {'gammaI\_j'};
M_.param_names_long(25) = {'gammaI_j'};
M_.param_names(26) = {'delta_j'};
M_.param_names_tex(26) = {'delta\_j'};
M_.param_names_long(26) = {'delta_j'};
M_.param_names(27) = {'S_j'};
M_.param_names_tex(27) = {'S\_j'};
M_.param_names_long(27) = {'S_j'};
M_.param_names(28) = {'eta_j'};
M_.param_names_tex(28) = {'eta\_j'};
M_.param_names_long(28) = {'eta_j'};
M_.param_names(29) = {'deltaW_j'};
M_.param_names_tex(29) = {'deltaW\_j'};
M_.param_names_long(29) = {'deltaW_j'};
M_.param_names(30) = {'thetaW_j'};
M_.param_names_tex(30) = {'thetaW\_j'};
M_.param_names_long(30) = {'thetaW_j'};
M_.param_names(31) = {'deltaD_j'};
M_.param_names_tex(31) = {'deltaD\_j'};
M_.param_names_long(31) = {'deltaD_j'};
M_.param_names(32) = {'thetaD_j'};
M_.param_names_tex(32) = {'thetaD\_j'};
M_.param_names_long(32) = {'thetaD_j'};
M_.param_names(33) = {'deltaN_j'};
M_.param_names_tex(33) = {'deltaN\_j'};
M_.param_names_long(33) = {'deltaN_j'};
M_.param_names(34) = {'thetaN_j'};
M_.param_names_tex(34) = {'thetaN\_j'};
M_.param_names_long(34) = {'thetaN_j'};
M_.param_names(35) = {'h_j'};
M_.param_names_tex(35) = {'h\_j'};
M_.param_names_long(35) = {'h_j'};
M_.param_names(36) = {'phiW_j'};
M_.param_names_tex(36) = {'phiW\_j'};
M_.param_names_long(36) = {'phiW_j'};
M_.param_names(37) = {'rhotau_j'};
M_.param_names_tex(37) = {'rhotau\_j'};
M_.param_names_long(37) = {'rhotau_j'};
M_.param_names(38) = {'rhodebt_j'};
M_.param_names_tex(38) = {'rhodebt\_j'};
M_.param_names_long(38) = {'rhodebt_j'};
M_.param_names(39) = {'n'};
M_.param_names_tex(39) = {'n'};
M_.param_names_long(39) = {'n'};
M_.param_names(40) = {'rho'};
M_.param_names_tex(40) = {'rho'};
M_.param_names_long(40) = {'rho'};
M_.param_names(41) = {'rho_j'};
M_.param_names_tex(41) = {'rho\_j'};
M_.param_names_long(41) = {'rho_j'};
M_.param_names(42) = {'psiY'};
M_.param_names_tex(42) = {'psiY'};
M_.param_names_long(42) = {'psiY'};
M_.param_names(43) = {'psiPI'};
M_.param_names_tex(43) = {'psiPI'};
M_.param_names_long(43) = {'psiPI'};
M_.param_names(44) = {'psiFPI'};
M_.param_names_tex(44) = {'psiFPI'};
M_.param_names_long(44) = {'psiFPI'};
M_.param_names(45) = {'psiTR'};
M_.param_names_tex(45) = {'psiTR'};
M_.param_names_long(45) = {'psiTR'};
M_.param_names(46) = {'psiY_j'};
M_.param_names_tex(46) = {'psiY\_j'};
M_.param_names_long(46) = {'psiY_j'};
M_.param_names(47) = {'psiPI_j'};
M_.param_names_tex(47) = {'psiPI\_j'};
M_.param_names_long(47) = {'psiPI_j'};
M_.param_names(48) = {'psiFPI_j'};
M_.param_names_tex(48) = {'psiFPI\_j'};
M_.param_names_long(48) = {'psiFPI_j'};
M_.param_names(49) = {'rhoG'};
M_.param_names_tex(49) = {'rhoG'};
M_.param_names_long(49) = {'rhoG'};
M_.param_names(50) = {'rhoT'};
M_.param_names_tex(50) = {'rhoT'};
M_.param_names_long(50) = {'rhoT'};
M_.param_names(51) = {'rhoD'};
M_.param_names_tex(51) = {'rhoD'};
M_.param_names_long(51) = {'rhoD'};
M_.param_names(52) = {'rhoN'};
M_.param_names_tex(52) = {'rhoN'};
M_.param_names_long(52) = {'rhoN'};
M_.param_names(53) = {'rhoC'};
M_.param_names_tex(53) = {'rhoC'};
M_.param_names_long(53) = {'rhoC'};
M_.param_names(54) = {'rhoL'};
M_.param_names_tex(54) = {'rhoL'};
M_.param_names_long(54) = {'rhoL'};
M_.param_names(55) = {'rhoI'};
M_.param_names_tex(55) = {'rhoI'};
M_.param_names_long(55) = {'rhoI'};
M_.param_names(56) = {'rhoG_j'};
M_.param_names_tex(56) = {'rhoG\_j'};
M_.param_names_long(56) = {'rhoG_j'};
M_.param_names(57) = {'rhoT_j'};
M_.param_names_tex(57) = {'rhoT\_j'};
M_.param_names_long(57) = {'rhoT_j'};
M_.param_names(58) = {'rhoD_j'};
M_.param_names_tex(58) = {'rhoD\_j'};
M_.param_names_long(58) = {'rhoD_j'};
M_.param_names(59) = {'rhoN_j'};
M_.param_names_tex(59) = {'rhoN\_j'};
M_.param_names_long(59) = {'rhoN_j'};
M_.param_names(60) = {'rhoC_j'};
M_.param_names_tex(60) = {'rhoC\_j'};
M_.param_names_long(60) = {'rhoC_j'};
M_.param_names(61) = {'rhoL_j'};
M_.param_names_tex(61) = {'rhoL\_j'};
M_.param_names_long(61) = {'rhoL_j'};
M_.param_names(62) = {'rhoI_j'};
M_.param_names_tex(62) = {'rhoI\_j'};
M_.param_names_long(62) = {'rhoI_j'};
M_.param_names(63) = {'sigmaG'};
M_.param_names_tex(63) = {'sigmaG'};
M_.param_names_long(63) = {'sigmaG'};
M_.param_names(64) = {'sigmaT'};
M_.param_names_tex(64) = {'sigmaT'};
M_.param_names_long(64) = {'sigmaT'};
M_.param_names(65) = {'sigmaD'};
M_.param_names_tex(65) = {'sigmaD'};
M_.param_names_long(65) = {'sigmaD'};
M_.param_names(66) = {'sigmaN'};
M_.param_names_tex(66) = {'sigmaN'};
M_.param_names_long(66) = {'sigmaN'};
M_.param_names(67) = {'sigmaC'};
M_.param_names_tex(67) = {'sigmaC'};
M_.param_names_long(67) = {'sigmaC'};
M_.param_names(68) = {'sigmaL'};
M_.param_names_tex(68) = {'sigmaL'};
M_.param_names_long(68) = {'sigmaL'};
M_.param_names(69) = {'sigmaI'};
M_.param_names_tex(69) = {'sigmaI'};
M_.param_names_long(69) = {'sigmaI'};
M_.param_names(70) = {'sigmaR'};
M_.param_names_tex(70) = {'sigmaR'};
M_.param_names_long(70) = {'sigmaR'};
M_.param_names(71) = {'sigmaG_j'};
M_.param_names_tex(71) = {'sigmaG\_j'};
M_.param_names_long(71) = {'sigmaG_j'};
M_.param_names(72) = {'sigmaT_j'};
M_.param_names_tex(72) = {'sigmaT\_j'};
M_.param_names_long(72) = {'sigmaT_j'};
M_.param_names(73) = {'sigmaD_j'};
M_.param_names_tex(73) = {'sigmaD\_j'};
M_.param_names_long(73) = {'sigmaD_j'};
M_.param_names(74) = {'sigmaN_j'};
M_.param_names_tex(74) = {'sigmaN\_j'};
M_.param_names_long(74) = {'sigmaN_j'};
M_.param_names(75) = {'sigmaC_j'};
M_.param_names_tex(75) = {'sigmaC\_j'};
M_.param_names_long(75) = {'sigmaC_j'};
M_.param_names(76) = {'sigmaL_j'};
M_.param_names_tex(76) = {'sigmaL\_j'};
M_.param_names_long(76) = {'sigmaL_j'};
M_.param_names(77) = {'sigmaI_j'};
M_.param_names_tex(77) = {'sigmaI\_j'};
M_.param_names_long(77) = {'sigmaI_j'};
M_.param_names(78) = {'Y_D_Y_ss'};
M_.param_names_tex(78) = {'Y\_D\_Y\_ss'};
M_.param_names_long(78) = {'Y_D_Y_ss'};
M_.param_names(79) = {'Y_N_Y_ss'};
M_.param_names_tex(79) = {'Y\_N\_Y\_ss'};
M_.param_names_long(79) = {'Y_N_Y_ss'};
M_.param_names(80) = {'C_Y_ss'};
M_.param_names_tex(80) = {'C\_Y\_ss'};
M_.param_names_long(80) = {'C_Y_ss'};
M_.param_names(81) = {'I_Y_ss'};
M_.param_names_tex(81) = {'I\_Y\_ss'};
M_.param_names_long(81) = {'I_Y_ss'};
M_.param_names(82) = {'G_Y_ss'};
M_.param_names_tex(82) = {'G\_Y\_ss'};
M_.param_names_long(82) = {'G_Y_ss'};
M_.param_names(83) = {'D_Y_ss'};
M_.param_names_tex(83) = {'D\_Y\_ss'};
M_.param_names_long(83) = {'D_Y_ss'};
M_.param_names(84) = {'TAX_Y_ss'};
M_.param_names_tex(84) = {'TAX\_Y\_ss'};
M_.param_names_long(84) = {'TAX_Y_ss'};
M_.param_names(85) = {'TR_Y_ss'};
M_.param_names_tex(85) = {'TR\_Y\_ss'};
M_.param_names_long(85) = {'TR_Y_ss'};
M_.param_names(86) = {'TC_TAX_ss'};
M_.param_names_tex(86) = {'TC\_TAX\_ss'};
M_.param_names_long(86) = {'TC_TAX_ss'};
M_.param_names(87) = {'TK_TAX_ss'};
M_.param_names_tex(87) = {'TK\_TAX\_ss'};
M_.param_names_long(87) = {'TK_TAX_ss'};
M_.param_names(88) = {'Y_D_Y_ss_j'};
M_.param_names_tex(88) = {'Y\_D\_Y\_ss\_j'};
M_.param_names_long(88) = {'Y_D_Y_ss_j'};
M_.param_names(89) = {'Y_N_Y_ss_j'};
M_.param_names_tex(89) = {'Y\_N\_Y\_ss\_j'};
M_.param_names_long(89) = {'Y_N_Y_ss_j'};
M_.param_names(90) = {'C_Y_ss_j'};
M_.param_names_tex(90) = {'C\_Y\_ss\_j'};
M_.param_names_long(90) = {'C_Y_ss_j'};
M_.param_names(91) = {'I_Y_ss_j'};
M_.param_names_tex(91) = {'I\_Y\_ss\_j'};
M_.param_names_long(91) = {'I_Y_ss_j'};
M_.param_names(92) = {'G_Y_ss_j'};
M_.param_names_tex(92) = {'G\_Y\_ss\_j'};
M_.param_names_long(92) = {'G_Y_ss_j'};
M_.param_names(93) = {'D_Y_ss_j'};
M_.param_names_tex(93) = {'D\_Y\_ss\_j'};
M_.param_names_long(93) = {'D_Y_ss_j'};
M_.param_names(94) = {'TAX_Y_ss_j'};
M_.param_names_tex(94) = {'TAX\_Y\_ss\_j'};
M_.param_names_long(94) = {'TAX_Y_ss_j'};
M_.param_names(95) = {'TR_Y_ss_j'};
M_.param_names_tex(95) = {'TR\_Y\_ss\_j'};
M_.param_names_long(95) = {'TR_Y_ss_j'};
M_.param_names(96) = {'TC_TAX_ss_j'};
M_.param_names_tex(96) = {'TC\_TAX\_ss\_j'};
M_.param_names_long(96) = {'TC_TAX_ss_j'};
M_.param_names(97) = {'TK_TAX_ss_j'};
M_.param_names_tex(97) = {'TK\_TAX\_ss\_j'};
M_.param_names_long(97) = {'TK_TAX_ss_j'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 15;
M_.endo_nbr = 64;
M_.param_nbr = 97;
M_.orig_endo_nbr = 64;
M_.aux_vars = [];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(15, 15);
M_.Correlation_matrix = eye(15, 15);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 64;
M_.eq_nbr = 64;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 1 40 0;
 2 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 3 46 104;
 4 47 105;
 5 48 0;
 6 49 0;
 7 50 106;
 8 51 107;
 9 52 0;
 10 53 0;
 0 54 0;
 0 55 0;
 11 56 108;
 12 57 109;
 13 58 0;
 14 59 0;
 0 60 110;
 0 61 111;
 15 62 112;
 16 63 113;
 0 64 0;
 0 65 0;
 0 66 114;
 0 67 115;
 0 68 0;
 0 69 0;
 17 70 116;
 18 71 117;
 19 72 118;
 20 73 119;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 21 80 0;
 22 81 0;
 23 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 24 88 0;
 25 89 0;
 26 90 120;
 27 91 121;
 28 92 122;
 29 93 123;
 30 94 0;
 31 95 0;
 32 96 0;
 33 97 0;
 34 98 124;
 35 99 125;
 36 100 0;
 37 101 0;
 38 102 0;
 39 103 0;]';
M_.nstatic = 21;
M_.nfwrd   = 4;
M_.npred   = 21;
M_.nboth   = 18;
M_.nsfwrd   = 22;
M_.nspred   = 39;
M_.ndynamic   = 43;
M_.dynamic_tmp_nbr = [13; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'y_D_i' ;
  2 , 'name' , 'y_D_j' ;
  3 , 'name' , 'y_N_i' ;
  4 , 'name' , 'y_N_j' ;
  5 , 'name' , 'y_i' ;
  6 , 'name' , 'y_j' ;
  7 , 'name' , '7' ;
  8 , 'name' , '8' ;
  9 , 'name' , 'q' ;
  10 , 'name' , 'k_i' ;
  11 , 'name' , 'k_j' ;
  12 , 'name' , 'r_K_i' ;
  13 , 'name' , 'r_K_j' ;
  14 , 'name' , '14' ;
  15 , 'name' , '15' ;
  16 , 'name' , 'q_T_i' ;
  17 , 'name' , 'q_T_j' ;
  18 , 'name' , 'l_i' ;
  19 , 'name' , 'l_j' ;
  20 , 'name' , '20' ;
  21 , 'name' , '21' ;
  22 , 'name' , 'MRS_i' ;
  23 , 'name' , 'MRS_j' ;
  24 , 'name' , 'pi_D_i' ;
  25 , 'name' , 'pi_D_j' ;
  26 , 'name' , 'pi_N_i' ;
  27 , 'name' , 'pi_N_j' ;
  28 , 'name' , 'MC_D_i' ;
  29 , 'name' , 'MC_D_j' ;
  30 , 'name' , 'MC_N_i' ;
  31 , 'name' , 'MC_N_j' ;
  32 , 'name' , '32' ;
  33 , 'name' , '33' ;
  34 , 'name' , 'pi_T_i' ;
  35 , 'name' , 'pi_T_j' ;
  36 , 'name' , 'pi_C_i' ;
  37 , 'name' , 'pi_C_j' ;
  38 , 'name' , '38' ;
  39 , 'name' , 'r' ;
  40 , 'name' , 'r_j' ;
  41 , 'name' , 'y_EMU' ;
  42 , 'name' , 'pi_C_EMU' ;
  43 , 'name' , '43' ;
  44 , 'name' , '44' ;
  45 , 'name' , 'g_i' ;
  46 , 'name' , 'g_j' ;
  47 , 'name' , 'tax_i' ;
  48 , 'name' , 'tax_j' ;
  49 , 'name' , 'tauC_i' ;
  50 , 'name' , 'tauC_j' ;
  51 , 'name' , 'tauK_i' ;
  52 , 'name' , 'tauK_j' ;
  53 , 'name' , 'tr_i' ;
  54 , 'name' , '54' ;
  55 , 'name' , 'a_D_i' ;
  56 , 'name' , 'a_D_j' ;
  57 , 'name' , 'a_N_i' ;
  58 , 'name' , 'a_N_j' ;
  59 , 'name' , 'epsilon_C_i' ;
  60 , 'name' , 'epsilon_C_j' ;
  61 , 'name' , 'epsilon_L_i' ;
  62 , 'name' , 'epsilon_L_j' ;
  63 , 'name' , 'epsilon_I_i' ;
  64 , 'name' , 'epsilon_I_j' ;
};
M_.mapping.y_i.eqidx = [5 39 41 53 ];
M_.mapping.y_j.eqidx = [6 40 41 53 ];
M_.mapping.y_D_i.eqidx = [1 5 18 ];
M_.mapping.y_D_j.eqidx = [2 6 19 ];
M_.mapping.y_N_i.eqidx = [3 5 18 ];
M_.mapping.y_N_j.eqidx = [4 6 19 ];
M_.mapping.c_i.eqidx = [1 2 3 7 9 22 47 ];
M_.mapping.c_j.eqidx = [1 2 4 8 9 23 48 ];
M_.mapping.x_i.eqidx = [1 2 3 14 28 30 32 38 ];
M_.mapping.x_j.eqidx = [1 2 4 15 29 31 33 38 ];
M_.mapping.i_i.eqidx = [1 2 3 10 14 ];
M_.mapping.i_j.eqidx = [1 2 4 11 15 ];
M_.mapping.g_i.eqidx = [3 43 45 ];
M_.mapping.g_j.eqidx = [4 44 46 ];
M_.mapping.tax_i.eqidx = [43 47 ];
M_.mapping.tax_j.eqidx = [44 48 ];
M_.mapping.pi_C_i.eqidx = [7 16 20 36 39 42 ];
M_.mapping.pi_C_j.eqidx = [8 17 21 37 40 42 ];
M_.mapping.k_i.eqidx = [10 12 47 ];
M_.mapping.k_j.eqidx = [11 13 48 ];
M_.mapping.r_K_i.eqidx = [12 16 18 28 30 47 ];
M_.mapping.r_K_j.eqidx = [13 17 19 29 31 48 ];
M_.mapping.w_i.eqidx = [12 18 20 28 30 ];
M_.mapping.w_j.eqidx = [13 19 21 29 31 ];
M_.mapping.l_i.eqidx = [12 18 22 ];
M_.mapping.l_j.eqidx = [13 19 23 ];
M_.mapping.q_T_i.eqidx = [14 16 ];
M_.mapping.q_T_j.eqidx = [15 17 ];
M_.mapping.MRS_i.eqidx = [20 22 ];
M_.mapping.MRS_j.eqidx = [21 23 ];
M_.mapping.pi_D_i.eqidx = [24 34 ];
M_.mapping.pi_D_j.eqidx = [25 35 ];
M_.mapping.pi_N_i.eqidx = [26 32 36 ];
M_.mapping.pi_N_j.eqidx = [27 33 37 ];
M_.mapping.MC_D_i.eqidx = [24 28 ];
M_.mapping.MC_D_j.eqidx = [25 29 ];
M_.mapping.MC_N_i.eqidx = [26 30 ];
M_.mapping.MC_N_j.eqidx = [27 31 ];
M_.mapping.pi_T_i.eqidx = [32 34 36 ];
M_.mapping.pi_T_j.eqidx = [33 35 37 ];
M_.mapping.t.eqidx = [1 2 28 29 34 35 38 ];
M_.mapping.r.eqidx = [7 16 39 43 ];
M_.mapping.r_j.eqidx = [8 17 40 44 ];
M_.mapping.q.eqidx = [9 38 ];
M_.mapping.y_EMU.eqidx = [41 ];
M_.mapping.pi_C_EMU.eqidx = [42 ];
M_.mapping.tr_i.eqidx = [43 53 54 ];
M_.mapping.tr_j.eqidx = [44 54 ];
M_.mapping.d_i.eqidx = [43 49 51 ];
M_.mapping.d_j.eqidx = [44 50 52 ];
M_.mapping.tauC_i.eqidx = [7 47 49 ];
M_.mapping.tauC_j.eqidx = [8 48 50 ];
M_.mapping.tauK_i.eqidx = [16 47 51 ];
M_.mapping.tauK_j.eqidx = [17 48 52 ];
M_.mapping.a_D_i.eqidx = [18 28 55 ];
M_.mapping.a_D_j.eqidx = [19 29 56 ];
M_.mapping.a_N_i.eqidx = [18 30 57 ];
M_.mapping.a_N_j.eqidx = [19 31 58 ];
M_.mapping.epsilon_C_i.eqidx = [7 9 22 59 ];
M_.mapping.epsilon_C_j.eqidx = [8 9 23 60 ];
M_.mapping.epsilon_L_i.eqidx = [22 61 ];
M_.mapping.epsilon_L_j.eqidx = [23 62 ];
M_.mapping.epsilon_I_i.eqidx = [10 14 63 ];
M_.mapping.epsilon_I_j.eqidx = [11 15 64 ];
M_.mapping.u_a_D_i.eqidx = [55 ];
M_.mapping.u_a_D_j.eqidx = [56 ];
M_.mapping.u_a_N_i.eqidx = [57 ];
M_.mapping.u_a_N_j.eqidx = [58 ];
M_.mapping.u_C_i.eqidx = [59 ];
M_.mapping.u_C_j.eqidx = [60 ];
M_.mapping.u_L_i.eqidx = [61 ];
M_.mapping.u_L_j.eqidx = [62 ];
M_.mapping.u_I_i.eqidx = [63 ];
M_.mapping.u_I_j.eqidx = [64 ];
M_.mapping.u_G_i.eqidx = [45 ];
M_.mapping.u_G_j.eqidx = [46 ];
M_.mapping.u_T_i.eqidx = [49 51 ];
M_.mapping.u_T_j.eqidx = [50 52 ];
M_.mapping.u_R.eqidx = [39 40 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [1 2 7 8 9 10 11 12 13 14 17 18 19 20 23 24 31 32 33 34 41 42 43 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 ];
M_.exo_names_orig_ord = [1:15];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(64, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(15, 1);
M_.params = NaN(97, 1);
M_.endo_trends = struct('deflator', cell(64, 1), 'log_deflator', cell(64, 1), 'growth_factor', cell(64, 1), 'log_growth_factor', cell(64, 1));
M_.NNZDerivatives = [298; -1; -1; ];
M_.static_tmp_nbr = [12; 2; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 1.5;
sigma = M_.params(1);
M_.params(20) = 1.5;
sigma_j = M_.params(20);
M_.params(2) = 2;
phi = M_.params(2);
M_.params(21) = 2;
phi_j = M_.params(21);
M_.params(3) = 0.9975;
beta = M_.params(3);
M_.params(22) = 0.9975;
beta_j = M_.params(22);
M_.params(4) = 0.5424;
gammaC = M_.params(4);
M_.params(23) = 0.5424;
gammaC_j = M_.params(23);
M_.params(5) = 0.8;
alpha = M_.params(5);
M_.params(24) = 0.8;
alpha_j = M_.params(24);
M_.params(6) = 0.4956;
gammaI = M_.params(6);
M_.params(25) = 0.4956;
gammaI_j = M_.params(25);
M_.params(7) = 0.1;
delta = M_.params(7);
M_.params(26) = 0.1;
delta_j = M_.params(26);
M_.params(8) = 4;
S = M_.params(8);
M_.params(27) = 4;
S_j = M_.params(27);
M_.params(9) = 0.3868;
eta = M_.params(9);
M_.params(28) = 0.3868;
eta_j = M_.params(28);
M_.params(10) = 0.1;
deltaW = M_.params(10);
M_.params(29) = 0.1;
deltaW_j = M_.params(29);
M_.params(11) = 0.7;
thetaW = M_.params(11);
M_.params(30) = 0.7;
thetaW_j = M_.params(30);
M_.params(12) = 0.1;
deltaD = M_.params(12);
M_.params(31) = 0.1;
deltaD_j = M_.params(31);
M_.params(13) = 0.7;
thetaD = M_.params(13);
M_.params(32) = 0.7;
thetaD_j = M_.params(32);
M_.params(14) = 0.1;
deltaN = M_.params(14);
M_.params(33) = 0.1;
deltaN_j = M_.params(33);
M_.params(15) = 0.7;
thetaN = M_.params(15);
M_.params(34) = 0.7;
thetaN_j = M_.params(34);
M_.params(16) = 0.5;
h = M_.params(16);
M_.params(35) = 0.5;
h_j = M_.params(35);
M_.params(17) = 3;
phiW = M_.params(17);
M_.params(36) = 3;
phiW_j = M_.params(36);
M_.params(18) = 0.7;
rhotau = M_.params(18);
M_.params(37) = 0.7;
rhotau_j = M_.params(37);
M_.params(19) = 0.7;
rhodebt = M_.params(19);
M_.params(38) = 0.7;
rhodebt_j = M_.params(38);
M_.params(39) = 0.5;
n = M_.params(39);
M_.params(40) = 0.7;
rho = M_.params(40);
M_.params(41) = 0.7;
rho_j = M_.params(41);
M_.params(42) = 1;
psiY = M_.params(42);
M_.params(43) = 4;
psiPI = M_.params(43);
M_.params(44) = 0.35;
psiFPI = M_.params(44);
M_.params(46) = 1;
psiY_j = M_.params(46);
M_.params(47) = 4;
psiPI_j = M_.params(47);
M_.params(45) = 0.0;
psiTR = M_.params(45);
M_.params(48) = 0.35;
psiFPI_j = M_.params(48);
M_.params(49) = 0.7;
rhoG = M_.params(49);
M_.params(50) = 0.7;
rhoT = M_.params(50);
M_.params(51) = 0.7;
rhoD = M_.params(51);
M_.params(52) = 0.7;
rhoN = M_.params(52);
M_.params(53) = 0.7;
rhoC = M_.params(53);
M_.params(54) = 0.7;
rhoL = M_.params(54);
M_.params(55) = 0.7;
rhoI = M_.params(55);
M_.params(56) = 0.7;
rhoG_j = M_.params(56);
M_.params(57) = 0.7;
rhoT_j = M_.params(57);
M_.params(58) = 0.7;
rhoD_j = M_.params(58);
M_.params(59) = 0.7;
rhoN_j = M_.params(59);
M_.params(60) = 0.7;
rhoC_j = M_.params(60);
M_.params(61) = 0.7;
rhoL_j = M_.params(61);
M_.params(62) = 0.7;
rhoI_j = M_.params(62);
M_.params(63) = 0.1;
sigmaG = M_.params(63);
M_.params(64) = 0.1;
sigmaT = M_.params(64);
M_.params(65) = 0.1;
sigmaD = M_.params(65);
M_.params(66) = 0.1;
sigmaN = M_.params(66);
M_.params(67) = 0.1;
sigmaC = M_.params(67);
M_.params(68) = 0.1;
sigmaL = M_.params(68);
M_.params(69) = 0.1;
sigmaI = M_.params(69);
M_.params(70) = 0.1;
sigmaR = M_.params(70);
M_.params(71) = 0.1;
sigmaG_j = M_.params(71);
M_.params(72) = 0.1;
sigmaT_j = M_.params(72);
M_.params(73) = 0.1;
sigmaD_j = M_.params(73);
M_.params(74) = 0.1;
sigmaN_j = M_.params(74);
M_.params(75) = 0.1;
sigmaC_j = M_.params(75);
M_.params(76) = 0.1;
sigmaL_j = M_.params(76);
M_.params(77) = 0.1;
sigmaI_j = M_.params(77);
M_.params(80) = 0.4946;
C_Y_ss = M_.params(80);
M_.params(81) = 0.2620;
I_Y_ss = M_.params(81);
M_.params(82) = 1-M_.params(80)-M_.params(81);
G_Y_ss = M_.params(82);
M_.params(79) = M_.params(80)*(1-M_.params(4))+M_.params(81)*(1-M_.params(6))+M_.params(82);
Y_N_Y_ss = M_.params(79);
M_.params(78) = 1-M_.params(79);
Y_D_Y_ss = M_.params(78);
M_.params(83) = 0.8;
D_Y_ss = M_.params(83);
M_.params(84) = 0.4;
TAX_Y_ss = M_.params(84);
M_.params(85) = 0.02;
TR_Y_ss = M_.params(85);
M_.params(90) = 0.4946;
C_Y_ss_j = M_.params(90);
M_.params(91) = 0.2620;
I_Y_ss_j = M_.params(91);
M_.params(92) = 1-M_.params(90)-M_.params(91);
G_Y_ss_j = M_.params(92);
M_.params(89) = M_.params(90)*(1-M_.params(23))+M_.params(91)*(1-M_.params(25))+M_.params(92);
Y_N_Y_ss_j = M_.params(89);
M_.params(88) = 1-M_.params(89);
Y_D_Y_ss_j = M_.params(88);
M_.params(93) = 0.8;
D_Y_ss_j = M_.params(93);
M_.params(94) = 0.4;
TAX_Y_ss_j = M_.params(94);
M_.params(95) = 0.02;
TR_Y_ss_j = M_.params(95);
M_.params(86) = 0.5;
TC_TAX_ss = M_.params(86);
M_.params(96) = 0.5;
TC_TAX_ss_j = M_.params(96);
M_.params(87) = 0.5;
TK_TAX_ss = M_.params(87);
M_.params(97) = 0.5;
TK_TAX_ss_j = M_.params(97);
%
% INITVAL instructions
%
options_.initval_file = false;
oo_.steady_state(1) = 0;
oo_.steady_state(2) = 0;
oo_.steady_state(3) = 0;
oo_.steady_state(4) = 0;
oo_.steady_state(5) = 0;
oo_.steady_state(6) = 0;
oo_.steady_state(7) = 0;
oo_.steady_state(8) = 0;
oo_.steady_state(9) = 0;
oo_.steady_state(10) = 0;
oo_.steady_state(11) = 0;
oo_.steady_state(12) = 0;
oo_.steady_state(13) = 0;
oo_.steady_state(14) = 0;
oo_.steady_state(17) = 0;
oo_.steady_state(18) = 0;
oo_.steady_state(19) = 0;
oo_.steady_state(20) = 0;
oo_.steady_state(21) = 0;
oo_.steady_state(22) = 0;
oo_.steady_state(23) = 0;
oo_.steady_state(24) = 0;
oo_.steady_state(25) = 0;
oo_.steady_state(26) = 0;
oo_.steady_state(27) = 0;
oo_.steady_state(28) = 0;
oo_.steady_state(29) = 0;
oo_.steady_state(30) = 0;
oo_.steady_state(31) = 0;
oo_.steady_state(32) = 0;
oo_.steady_state(33) = 0;
oo_.steady_state(34) = 0;
oo_.steady_state(35) = 0;
oo_.steady_state(36) = 0;
oo_.steady_state(37) = 0;
oo_.steady_state(38) = 0;
oo_.steady_state(39) = 0;
oo_.steady_state(40) = 0;
oo_.steady_state(41) = 0;
oo_.steady_state(42) = 0;
oo_.steady_state(43) = 0;
oo_.steady_state(44) = 0;
oo_.steady_state(45) = 0;
oo_.steady_state(46) = 0;
oo_.steady_state(47) = 0;
oo_.steady_state(48) = 0;
oo_.steady_state(49) = 0;
oo_.steady_state(50) = 0;
oo_.steady_state(55) = 0;
oo_.steady_state(56) = 0;
oo_.steady_state(57) = 0;
oo_.steady_state(58) = 0;
oo_.steady_state(59) = 0;
oo_.steady_state(60) = 0;
oo_.steady_state(61) = 0;
oo_.steady_state(62) = 0;
oo_.steady_state(63) = 0;
oo_.steady_state(64) = 0;
oo_.steady_state(51) = 0;
oo_.steady_state(52) = 0;
oo_.steady_state(53) = 0;
oo_.steady_state(54) = 0;
oo_.steady_state(15) = 0;
oo_.steady_state(16) = 0;
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(15, 15) = M_.params(70)^2;
options_.irf = 20;
options_.nocorr = true;
options_.nomoments = true;
options_.order = 1;
var_list_ = {'y_i';'y_j';'c_i';'c_j';'i_i';'i_j';'r';'r_j';'k_i';'k_j';'q';'t';'x_i';'x_j';'l_i';'l_j';'w_i';'w_j';'pi_C_i';'pi_C_j';'tr_i';'tr_j';'d_i';'d_j';'tax_i';'tax_j';'tauC_i';'tauC_j';'tauK_i';'tauK_j';'y_D_i';'y_D_j';'y_N_i';'q_T_i';'q_T_j';'MRS_i';'MRS_j';'pi_D_i';'pi_D_j';'pi_N_i';'pi_N_j';'MC_D_i';'MC_D_j';'MC_N_i';'MC_N_j';'pi_T_i';'pi_T_j'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'Model_Loes_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Model_Loes_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Model_Loes_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Model_Loes_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Model_Loes_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Model_Loes_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Model_Loes_results.mat'], 'oo_recursive_', '-append');
end
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
